### PR TITLE
Let the travis-ci response fail to be json.

### PR DESCRIPTION
**Pull request by ericdill**
Also print out what the response actually is.

Maybe addresses #233.

Any idea how one would go about testing this?

### CODE REVIEW

**Comment by ericdill** [comment]
> Any idea how one would go about testing this?

Oh maybe what this should do is *not* eat the exception, but just print out whatever `response` is and then let the exception bubble up. That way this is not modifying the current behavior of smithy, but potentially giving us some more information about what is going on since this seems to be occurring again on staged-recipes master

**Comment by jakirkham** [comment]
Thanks for giving this some thought, @ericdill. Yeah the story with automatically configuring CIs with feedstocks has not been a good one (particularly of late). Travis, in particular, has been translucent about helping clarify what is going on so we can fix. Maybe they will be better if we end up paying for services? Though certainly Travis CI is not the only one with this issue. AppVeyor has been flaky at times too, but we do have a better idea of some of the problems in that case.

TBH I'm leaning towards having some auto restart with staged-recipes as described in issue ( https://github.com/conda-forge/staged-recipes/issues/2619 ) at this point. After all that seems to be the source of this flakiness (manual use of `conda-smithy` rarely has issues). We already do this with partial conversion failure. So it shouldn't be difficult to extend to total conversion failure. Since we suppress retries on completed conversion, this shouldn't run us into any trouble. What do you think?

**Comment by ericdill** [comment]
I think an auto-restart makes sense. It is not the most elegant way to fix this issue, but it should definitely be better than the current state of things. Can you go ahead and enable auto restarting and I can iterate on a more granular fix as time and interest permits?

3 or 5 retries seems like a sensible starting point.

**Comment by jakirkham** [comment]
So this will take a little coding on my part. It's not bad, but it's not flipping a switch either. Just letting you know.

FWIW I'm suspicious that Travis CI is doing something really silly when one pushes the sync button (as we need to do here). So I'm not sure if there is an elegant solution on our end, but there might be on there's. ( https://github.com/travis-ci/travis-ci/issues/6320 ) This also raises some questions about long term solutions as well.

**Comment by ericdill** [comment]
> So this will take a little coding on my part. It's not bad, but it's not flipping a switch either. Just letting you know.

Definitely. Thanks for clarifying. I misunderstood what you were proposing. I literally thought there was an "auto restart" feature on the travis-ci configs somewhere. 🤦‍♂️

**Comment by ericdill** [comment]
I'm curious what the text of the response is. Do you think we could get this in since it doesn't change the behavior of conda-smithy?

**Comment by ericdill** [comment]
> Was more trying to share some thoughts on this problem generally

For sure. Let's keep discussing this issue

> we might want to check it doesn't print out the token

yeesh, good point. I sure hope travis doesn't do this...

**Comment by minrk** [comment]
I noticed that error codes aren't being checked (#503) and there's a pretty good chance that Travis is responding with an error here. The text is just 'access denied' for an incorrect token, for instance.

My *guess* is that Travis may have flagged the access token for some reason and blocked it. This ought to show up as a 403 error. If this is the case, issuing a new token should solve the issue.

It could also be Travis failing to deal with the size of the response for some reason, in which case there would hopefully be a 5XX error. Not as much we could do about that, though.

Potentially useful: All responses from Travis include a `X-Request-Id` header containing a UUID identifying the request, presumably for their own debugging purposes. If this is a regular thing, logging the request ID for failed requests may be useful for getting support from Travis.

**Pull request merged**
