### PR TITLE
Only try to upload if previous steps succeeded on azure (osx + win)

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Added a ``news`` entry

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks! Please add a news entry

**Comment by hmaarrfk** [comment]
Thanks for the review. I think this news entry should do.

**Comment by isuruf** [comment]
Did you check this with a feedstock? If so, +1 to merge

**Comment by hmaarrfk** [comment]
I checked it in personal feedstocks a while back (At the time of development) that said, I forget which exact feedstock so I can't point to one.

**Comment by scopatz** [comment]
That is good enough for me

**Pull request merged**
