### PR TITLE
fix feedstock_io.py on windows

### LINKED ISSUE #2185: BUG: failed git detection (despite it being on PATH) on windows
With 3.45.0, I get

```
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.
```

It's definitely on my path though
```
>where git
C:\Users\[xxx]\.pixi\envs\git\Library\bin\git.exe
C:\Users\[xxx]\.pixi\bin\git.bat
```

### PR DESCRIPTION
**Pull request by h-vetinari**
Fixes #2185, based on a suggestion by @mgorny

### CODE REVIEW

**Comment by mgorny** [comment]
Thanks but I'm working on a cleaner fix. I'm just setting up a Windows test environment to test it better.

**Comment by beckermr** [comment]
FWIW this fix seems fine to me.

**Comment by mgorny** [comment]
> FWIW this fix seems fine to me.

Well, I'm not going to insist. I wanted to switch over to `pathlib.Path(...).as_posix()`, so that the substitution is done only on Windows.

**Comment by mgorny** [comment]
Either case, I'm going to recheck the code for other similar problems. Wrt https://github.com/libgit2/libgit2/blob/main/docs/conventions.md#external-api, all paths internal to git must use forward slashes.

**Comment by h-vetinari** [comment]
Superseded by #2192

**Pull request closed without merging**
