### PR TITLE
Used MANIFEST for setup.py resource management.

### PR DESCRIPTION
**Pull request by pelson**
Ping @scopatz

### CODE REVIEW

**Comment by scopatz** [comment]
This doesn't seem to actually copy the `feedstock_content` dir. Here is what I get when install

```console
scopatz@athenaie ~/conda-smithy pelson-setup_manifest $ rm -r conda_smithy.egg-info/ build/ dist/
scopatz@athenaie ~/conda-smithy pelson-setup_manifest $ ./setup.py install --user
/home/scopatz/miniconda3/lib/python3.4/site-packages/setuptools-18.0.1-py3.4.egg/setuptools/dist.py:285: UserWarning: Normalizing '0.1.0dev0' to '0.1.0.dev0'
running install
running bdist_egg
running egg_info
creating conda_smithy.egg-info
writing conda_smithy.egg-info/PKG-INFO
writing top-level names to conda_smithy.egg-info/top_level.txt
writing requirements to conda_smithy.egg-info/requires.txt
writing dependency_links to conda_smithy.egg-info/dependency_links.txt
writing manifest file 'conda_smithy.egg-info/SOURCES.txt'
reading manifest file 'conda_smithy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'conda_smithy.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/conda_smithy
copying conda_smithy/__init__.py -> build/lib/conda_smithy
copying conda_smithy/configure_circle_ci.py -> build/lib/conda_smithy
copying conda_smithy/configure_feedstock.py -> build/lib/conda_smithy
creating build/lib/conda_smithy/tests
copying conda_smithy/tests/test_configure_feedstock.py -> build/lib/conda_smithy/tests
copying conda_smithy/tests/__init__.py -> build/lib/conda_smithy/tests
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/conda_smithy
creating build/bdist.linux-x86_64/egg/conda_smithy/tests
copying build/lib/conda_smithy/tests/test_configure_feedstock.py -> build/bdist.linux-x86_64/egg/conda_smithy/tests
copying build/lib/conda_smithy/tests/__init__.py -> build/bdist.linux-x86_64/egg/conda_smithy/tests
copying build/lib/conda_smithy/__init__.py -> build/bdist.linux-x86_64/egg/conda_smithy
copying build/lib/conda_smithy/configure_circle_ci.py -> build/bdist.linux-x86_64/egg/conda_smithy
copying build/lib/conda_smithy/configure_feedstock.py -> build/bdist.linux-x86_64/egg/conda_smithy
byte-compiling build/bdist.linux-x86_64/egg/conda_smithy/tests/test_configure_feedstock.py to test_configure_feedstock.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/conda_smithy/tests/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/conda_smithy/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/conda_smithy/configure_circle_ci.py to configure_circle_ci.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/conda_smithy/configure_feedstock.py to configure_feedstock.cpython-34.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/scripts-3.4
copying and adjusting scripts/conda-smithy -> build/scripts-3.4
changing mode of build/scripts-3.4/conda-smithy from 664 to 775
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.4/conda-smithy -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/conda-smithy to 775
copying conda_smithy.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying conda_smithy.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying conda_smithy.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying conda_smithy.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying conda_smithy.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying conda_smithy.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/conda_smithy-0.1.0.dev0-py3.4.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing conda_smithy-0.1.0.dev0-py3.4.egg
removing '/home/scopatz/.local/lib/python3.4/site-packages/conda_smithy-0.1.0.dev0-py3.4.egg' (and everything under it)
creating /home/scopatz/.local/lib/python3.4/site-packages/conda_smithy-0.1.0.dev0-py3.4.egg
Extracting conda_smithy-0.1.0.dev0-py3.4.egg to /home/scopatz/.local/lib/python3.4/site-packages
conda-smithy 0.1.0.dev0 is already the active version in easy-install.pth
Installing conda-smithy script to /home/scopatz/.local/bin

Installed /home/scopatz/.local/lib/python3.4/site-packages/conda_smithy-0.1.0.dev0-py3.4.egg
Processing dependencies for conda-smithy==0.1.0.dev0
Searching for conda==3.15.1
Best match: conda 3.15.1
Adding conda 3.15.1 to easy-install.pth file

Using /home/scopatz/miniconda3/lib/python3.4/site-packages
Searching for conda-build==1.14.1
Best match: conda-build 1.14.1
Adding conda-build 1.14.1 to easy-install.pth file

Using /home/scopatz/miniconda3/lib/python3.4/site-packages
Searching for requests==2.7.0
Best match: requests 2.7.0
Adding requests 2.7.0 to easy-install.pth file

Using /home/scopatz/miniconda3/lib/python3.4/site-packages
Searching for Jinja2==2.7.3
Best match: Jinja2 2.7.3
Adding Jinja2 2.7.3 to easy-install.pth file

Using /home/scopatz/miniconda3/lib/python3.4/site-packages
Finished processing dependencies for conda-smithy==0.1.0.dev0
```

Here is then what I get when I try to run on an example dir, `xonsh`.

```console
scopatz@athenaie ~ $ conda smithy init xonsh/recipe --feedstock-directory xonsh-feedstockTraceback (most recent call last):
  File "/home/scopatz/.local/bin/conda-smithy", line 4, in <module>
    __import__('pkg_resources').run_script('conda-smithy==0.1.0.dev0', 'conda-smithy')
  File "/home/scopatz/miniconda3/lib/python3.4/site-packages/setuptools-18.0.1-py3.4.egg/pkg_resources/__init__.py", line 735, in run_script
  File "/home/scopatz/miniconda3/lib/python3.4/site-packages/setuptools-18.0.1-py3.4.egg/pkg_resources/__init__.py", line 1652, in run_script
  File "/home/scopatz/.local/lib/python3.4/site-packages/conda_smithy-0.1.0.dev0-py3.4.egg/EGG-INFO/scripts/conda-smithy", line 161, in <module>
    args.subcommand_func(args)
  File "/home/scopatz/.local/lib/python3.4/site-packages/conda_smithy-0.1.0.dev0-py3.4.egg/EGG-INFO/scripts/conda-smithy", line 64, in __call__
    generate_feedstock_content(feedstock_directory, args.recipe_directory)
  File "/home/scopatz/.local/lib/python3.4/site-packages/conda_smithy-0.1.0.dev0-py3.4.egg/EGG-INFO/scripts/conda-smithy", line 24, in generate_feedstock_content
    configure_feedstock.main(target_directory)
  File "/home/scopatz/.local/lib/python3.4/site-packages/conda_smithy-0.1.0.dev0-py3.4.egg/conda_smithy/configure_feedstock.py", line 179, in main
    copy_feedstock_content(forge_dir)
  File "/home/scopatz/.local/lib/python3.4/site-packages/conda_smithy-0.1.0.dev0-py3.4.egg/conda_smithy/configure_feedstock.py", line 77, in copy_feedstock_content
    copytree(feedstock_content, forge_dir, 'README')
  File "/home/scopatz/.local/lib/python3.4/site-packages/conda_smithy-0.1.0.dev0-py3.4.egg/conda_smithy/configure_feedstock.py", line 61, in copytree
    for item in os.listdir(src):
FileNotFoundError: [Errno 2] No such file or directory: '/home/scopatz/.local/lib/python3.4/site-packages/conda_smithy-0.1.0.dev0-py3.4.egg/conda_smithy/feedstock_content'
```

**Comment by mwcraig** [comment]
Odd...in python 2 and 3 this works for me change works for me.

```bash
$
conda smithy init /Users/mcraig/Development/conda/conda-recipes/mrjob --feedstock-directory foo/bar
Initialized empty Git repository in /Users/mcraig/Downloads/foo/foo/bar/.git/
[master (root-commit) 9047c73] Initial commit of the mrjob feedstock.
 11 files changed, 407 insertions(+)
 create mode 100644 .travis.yml
 create mode 100644 README
 create mode 100644 appveyor.yml
 create mode 100644 ci_support/__pycache__/upload_or_check_non_existence.cpython-34.pyc
 create mode 100755 ci_support/run_docker_build.sh
 create mode 100644 ci_support/upload_or_check_non_existence.py
 create mode 100644 circle.yml
 create mode 100644 conda-forge.yml
 create mode 100644 recipe/bld.bat
 create mode 100644 recipe/build.sh
 create mode 100644 recipe/meta.yaml
```

**Comment by mwcraig** [comment]
@scopatz -- did you maybe have an old install of conda-smithy still in place?

**Comment by scopatz** [comment]
I am on py3k for what it is worth.

**Comment by mwcraig** [comment]
I tried using it in both python2 and python3 (via miniconda and miniconda3). If you delete `/home/scopatz/.local/lib/python3.4/site-packages/conda_smithy-0.1.0.dev0-py3.4.egg` then try re-installing does it work?

**Comment by scopatz** [comment]
Just tried that, and it fails with the same error. The `feedstock_content` dir is not being copied correctly anymore:

```console
$ ls /home/scopatz/.local/lib/python3.4/site-packages/conda_smithy-0.1.0.dev0-py3.4.egg/conda_smithy/
configure_circle_ci.py  configure_feedstock.py  tests  __init__.py  __pycache__
```

You might have an old directory present if it is working for you...

**Comment by mwcraig** [comment]
Huh. That is weird.

I just removed conda-smithy from my miniconda3 install, then did `python setup.py install` and got the `feedstock_content` direction:

```
$ ls ~/miniconda3/lib/python3.4/site-packages/conda_smithy-0.1.0.dev0-py3.4.egg/conda_smithy/
__init__.py            conda_smithy.py        configure_feedstock.py templates
__pycache__            configure_circle_ci.py feedstock_content      tests
```

The only difference I see between what we are doing is that you are installing with `--user`.

But I just tried that, I'm seeing `feedstock_content` there too. About to try `git clean -fxd`...

**Comment by mwcraig** [comment]
Well, crap. Now it doesn't work for me.

**Comment by scopatz** [comment]
At least I am not totally crazy :)

**Comment by mwcraig** [comment]
OK, got the fix, just need to add `include_package_data=True` to `setup.py`. PR coming to @pelson's branch in a moment.

**Comment by pelson** [comment]
Thanks for your help guys.

> OK, got the fix, just need to add include_package_data=True to setup.py

I really hate this stuff. :cry:

**Comment by pelson** [comment]
Conflicts from https://github.com/conda-forge/conda-smithy/pull/9. I'll rebase.

**Comment by mwcraig** [comment]
@pelson -- will you have a chance to rebase this in the next couple of days? If not, I can...

**Comment by pelson** [comment]
Thanks for the ping @mwcraig . Rebased.

**Comment by mwcraig** [comment]
Installs fine now on both py2 and py3, so merging. Thanks, @pelson

**Pull request merged**
