### PR TITLE
Fix AppVeyor badge again

### PR DESCRIPTION
**Pull request by jakirkham**
Another tweak to how we handle AppVeyor badges following PR ( https://github.com/conda-forge/conda-smithy/pull/195 ).

Appears that AppVeyor made a change to how they handle the badge icon (not the link). In particular, they now want to keep underscores ( `_` ) in the icon if they can. See PR ( https://github.com/conda-forge/line_profiler-feedstock/pull/2 ) for an example of this problem or any feedstock building on AppVeyor that has an underscore. So this is a tweak to handle that problem.

Examples of this re-rendering can be seen in the PRs below.

* https://github.com/conda-forge/line_profiler-feedstock/pull/4
* https://github.com/conda-forge/pyomo.extras-feedstock/pull/10 (no-op as expected)
* https://github.com/conda-forge/thredds_crawler-feedstock/pull/8

Used the commit immediately after [`v1.0.3`]( https://github.com/conda-forge/conda-smithy/releases/tag/v1.0.3 ), which is commit ( https://github.com/conda-forge/conda-smithy/commit/cc27a51e366c7df42c5998c953f9193b112ccdd1 ). Did this to reduce noise in the diffs. Also re-rendered after solving merge conflicts with `master`. The AppVeyor badges were unchanged in all cases and remained visible.

### CODE REVIEW

**Comment by jakirkham** [comment]
Any thoughts on this, @pelson? While it is a largely uninteresting PR, it does fix the AppVeyor badges again. Though I'm wondering if that is now a moving target.

**Comment by pelson** [comment]
Nothing against this change. It would be handy to let @FeodorFitsner know that we are having a few issues with the AppVeyor repo & badge naming conventions. We would be happy for these to change for the better, but it would be useful if they could be done as infrequently as possible.

**Comment by jakirkham** [comment]
Yep, sounds reasonable. I'll make sure to open an issue.

**Comment by jakirkham** [comment]
See issue ( https://github.com/appveyor/ci/issues/1000 ).

**Pull request merged**
