### PR TITLE
Bump Azure's vmImage to macos-11

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [x] Added a ``news`` entry

See https://github.com/conda-forge/conda-forge.github.io/issues/1798

### CODE REVIEW

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
cc @beckermr

**Review by beckermr — APPROVED** [review]

**Comment by beckermr** [comment]
@jaimergp @jakirkham We should submit an announcement to the docs repo before merging this.

**Comment by jakirkham** [comment]
Makes sense. JFYI these live [here]( https://github.com/conda-forge/conda-forge.github.io/blob/main/src/user/announcements.rst )

**Comment by beckermr** [comment]
https://github.com/conda-forge/conda-forge.github.io/pull/1803

**Comment by ocefpaf** [comment]
I guess we need a new release with this ASAP.

**Comment by beckermr** [comment]
release is done - feedstock building now and everything should be live in an hour or so

**Pull request merged**
