### PR TITLE
travis template: Change `before install` to `before_install`.

### PR DESCRIPTION
**Pull request by jakirkham**

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @ocefpaf @pelson

**Comment by jakirkham** [comment]
Looks like it is passing. Should we merge? Would be nice to have as a release.

**Comment by jakirkham** [comment]
Thanks @ocefpaf.

**Comment by ocefpaf** [comment]
Things are OK in staged recipes and, after the release, we'll have re-issue the `MNT` PRs. I guess it is better to leave this to @pelson tomorrow morning.

(Although we should start taking turns in doing that at some point.)

**Comment by jakirkham** [comment]
Just as FYI, this fixes it. See this [log line]( https://travis-ci.org/conda-forge/cmt-feedstock/jobs/121268065#L154 ) due to the [same change]( https://github.com/conda-forge/cmt-feedstock/pull/2/commits/60929f1a8656c7cc833391c0c57e9bcd7e3c1fdc#diff-354f30a63fb0907d4ad57269548329e3R16 ).

**Comment by jakirkham** [comment]
Ok, that sounds good to me.

Well, I don't think I have commit privileges on this. Honestly, I have been happy to let @pelson run the show with conda-smithy. Though I guess I wouldn't mind merging small things like this if it helps.

**Comment by ocefpaf** [comment]
I meant the `MNT` PRs, but conda-smithy is tied to the hip to that...

**Comment by jakirkham** [comment]
What are we using to automate that? I don't think I know how that works yet.

**Comment by ocefpaf** [comment]
> What are we using to automate that? I don't think I know how that works yet.

Neither do I! That is my point. We need to know in case @pelson goes :surfer: :mount_fuji: :bicyclist: for a while.

**Comment by jakirkham** [comment]
I'm not even sure if it is webhosted. Maybe we should have a Heroku service for that too.

**Comment by jakirkham** [comment]
Minor note: We are downloading Miniconda with `wget` and we need to switch to `curl` as Mac only comes with `curl` by default. Fortunately, this is trivial. I can do it later or if you want to do it @ocefpaf feel free.

**Comment by ocefpaf** [comment]
I was just thinking about that :smile:

I am going to bed early today. If you haven't done it by tomorrow morning I can do it :wink:

**Comment by jakirkham** [comment]
No worries. Here is the PR ( https://github.com/conda-forge/conda-smithy/pull/123 ).

**Comment by pelson** [comment]
> Well, I don't think I have commit privileges on this. Honestly, I have been happy to let @pelson run the show with conda-smithy. Though I guess I wouldn't mind merging small things like this if it helps.

I've added this repo to the webservices team. That should give you permissions on here @jakirkham.

>> What are we using to automate that? I don't think I know how that works yet.

> Neither do I! That is my point. We need to know in case @pelson goes :surfer: :mount_fuji: :bicyclist: for a while.

It isn't in an obvious place: https://github.com/conda-forge/conda-forge.github.io/blob/master/scripts/regenerate_feedstock.py
I just run that. It pretty much takes care of itself. My directory structure looks like:

```
$HOME/dev/conda-forge/
                      conda-forge.github.io
                      feedstocks
```

I have a conda-forge-admin personal access token in my ```$HOME/.conda-smithy/github.token``` (at the moment that needs to be for conda-forge-admin though).

I then run:
```
conda execute -fv $HOME/dev/conda-forge/conda-forge.github.io/scripts/regenerate_feedstock.py --feedstock-dir $HOME/dev/conda-forge/feedstocks
```

That goes away and clones *every* feedstock locally, rerenders, if there are changes, it forks on github and pushes a branch + PR to the appropriate feedstock.

I'd be happy enough to share the token with both of you so that you can have a go (the worst you can do is open a PR which doesn't get merged).

I've been thinking about setting up a webservice which proposes a PR against feedstock PRs if the feedstock needs re-rendering. The workflow:

 * user submits a PR changing a small detail (such as the version number)
 * webservice runs to determine if the feedstock needed re-rendering after the change
   * if so, a PR is opened against the original PR which tells the user that the feedstock was out of date, and these are the changes needed to pull it up to date. The user can choose to merge or not, but they also have the necessary advice to inform them how to rerender a feedstock with conda-smithy.

**Comment by jakirkham** [comment]
> I've added this repo to the webservices team. That should give you permissions on here @jakirkham.

Hmm...then maybe there is something weird going on with the permissions here.

> It isn't in an obvious place: https://github.com/conda-forge/conda-forge.github.io/blob/master/scripts/regenerate_feedstock.py

Ahh...ok. Thanks for explaining how all this works. What are your thoughts on adding this to the Travis CI build matrix for the conda-forge.github.io repo?

**Comment by pelson** [comment]
> Ahh...ok. Thanks for explaining how all this works. What are your thoughts on adding this to the Travis CI build matrix for the conda-forge.github.io repo?

It is a nice place to have it. I'm keen to debounce too many requests though - 10-20 PRs at a time is about the maximum I want to be producing in an hour (and even then, in some situations that would be too many).

**Comment by jakirkham** [comment]
> It is a nice place to have it.

Cool, sounds like we agree.

> I'm keen to debounce too many requests though - 10-20 PRs at a time is about the maximum I want to be producing in an hour 

:+1: How do you propose to do this?

> ...even then, in some situations that would be too many

What situations do you have in mind?

**Comment by pelson** [comment]
> What situations do you have in mind?

GDAL, libnetcdf + anything else which takes a long time to build would block up the backlog. One option I guess would be to *inspect* the AppVeyor queue and figure out how much demand there was... sounds like it could sink a lot of time to write though... 😄

**Comment by jakirkham** [comment]
> GDAL, libnetcdf + anything else which takes a long time to build would block up the backlog.

Good point.

> One option I guess would be to inspect the AppVeyor queue and figure out how much demand there was... sounds like it could sink a lot of time to write though... :smile:

Ouch! Yeah, that does sound painful. Though I think you know what I will say. :smile:

"Premature optimization is the root of all evil." -- Donald Knuth

An easier strategy to me sounds like just picking an even lower number of feedstocks to update at a time.

Though maybe having this be totally automated is a bit premature. We have done 6 updates to `conda-smithy` in the past 2 weeks. Perhaps we can just simplify the steps required and decentralize the process.

For instance, setting something up where we can push a button and it will start this update process. We can add this stuff to a new repo so it has its own Travis CI instance and setup permissions for those that need it. Once we understand it better, we could merge it back here.

**Pull request merged**
