### PR TITLE
Change "User-Agent" in Travis CI header

### PR DESCRIPTION
**Pull request by jakirkham**
So, the `User-Agent` was added to the Travis CI request header in this PR ( https://github.com/conda-forge/conda-smithy/pull/36 ). Not quite sure why this particular `User-Agent` was chosen. Maybe it was just copied from the example in the [Travis CI docs]( https://docs.travis-ci.com/api#with-a-github-token )? Unfortunately Travis CI's docs are mum on this AFAICT. Though they do drop the pearl of wisdom below. Maybe we have to login with the bot periodically? Yuck, but if that helps it should be pretty easy to do.

> Note that therefore the API cannot be used to create new user accounts. The user will have to log in at least once via the web interface before interfacing with the API by other means.

While this seemed to work fine for awhile, it now is causing us grief when trying to generate some feedstocks. Here are some cases where it has failed ( https://github.com/conda-forge/staged-recipes/issues/900#issuecomment-229178358 ) ( https://github.com/conda-forge/staged-recipes/issues/923#issuecomment-229826566 ) ( https://github.com/conda-forge/staged-recipes/issues/923#issuecomment-229828379 ). Though it is not every feedstock that suffers from this issue, it definitely recurs with the same feedstock reliably. In other words, this is really just a brick wall that we hit sometimes, but when we hit we can't go past it.

At @isuruf found this gem ( https://github.com/travis-ci/travis-ci/issues/5649 ), which suggest setting the `User-Agent` to `Travis/1.0`. Though the issue seems to compare this to having no user agent, which is a known failure as pointed out in this [code comment]( https://github.com/conda-forge/conda-smithy/pull/36/files#diff-8666415dcccfaf789819c990341084c8R110 ) from PR ( https://github.com/conda-forge/conda-smithy/pull/36 ). We did have `User-Agent` set to something here, but it just wan't `Travis/1.0`. Here we change it to `Travis/1.0`. I don't really have a good explanation or any evidence for why this should be a better `User-Agent`. That being said, people seem to be having success with it. Maybe we should give it a go?

### CODE REVIEW

**Comment by pelson** [comment]
Without that specific user-agent, I most certainly wasn't able to refresh the repos on TravisCI. I suspect their code has changed, and it now requires a different user-agent. I have no qualms about changing the user agent in this way. 👍 
I'll push out a minor release version so that we can see the benefit immediately.
I'm also planning on moving forwards with a conda-smithy release ASAP (as in, I'm starting to work on it once I have cleared staged-recipes).

**Comment by jakirkham** [comment]
I'm sorry I can't verify this better. I did as much research as I could. Travis CI really could make this user-agent point much clearer IMHO. At least there were use cases where people were getting mileage out of this one.

**Comment by jakirkham** [comment]
> I'm also planning on moving forwards with a conda-smithy release ASAP (as in, I'm starting to work on it once I have cleared staged-recipes).

FWIW I think they are entangled. Basically, we may need this change to clear staged-recipes. See this depressing monologue starting with this [comment]( https://github.com/conda-forge/staged-recipes/issues/923#issuecomment-229826566 ).

**Comment by jakirkham** [comment]
Also, apparently this issue ( https://github.com/conda-forge/staged-recipes/issues/375 ) from a long time ago also encountered this problem.

**Comment by jakirkham** [comment]
I can't help but wonder if this was red-herring now.

**Comment by pelson** [comment]
Agreed. No harm done in it though.

**Comment by jakirkham** [comment]
Did you see this [comment]( https://github.com/travis-ci/travis-ci/issues/5649#issuecomment-230044386 )? Other people don't seem to be affected. Maybe this is still a valuable bug fix. If that's the case, we should try this anyways. Honestly the worst case is we still can't convert things to feedstocks, right? Thoughts on giving this a go in a 0.10.5 release?

**Pull request merged**
