### PR TITLE
Add Go, Rust license bundling check

### PR DESCRIPTION
**Pull request by BastianZim**
Checklist
* [x] Added a ``news`` entry

This adds a linter that checks if go, rust licenses are bundled. More info is here: https://conda-forge.org/docs/maintainer/adding_pkgs/#licenses-of-included-dependencies

### CODE REVIEW

**Comment by BastianZim** [comment]
pre-commit.ci autofix

**Comment by BastianZim** [comment]
pre-commit.ci autofix

**Comment by BastianZim** [comment]
Tests are failing because of an unrelated test. I'll see what the issue is.

**Comment by BastianZim** [comment]
Seems like `fitsio` is not in https://raw.githubusercontent.com/regro/cf-graph-countyfair/master/mappings/pypi/name_mapping.yaml anymore(?) which is breaking the test.

@conda-forge/core Should I try and fix this?

**Comment by beckermr** [comment]
I'd just change the test to use another package on pypi. Maybe numpy?

**Comment by BastianZim** [comment]
Sure! But it is a valid package. Should I open an issue somewhere that it's not in the yaml?

**Comment by BastianZim** [comment]
I guess that fixed it. CC @beckermr

**Comment by beckermr** [comment]
> Sure! But it is a valid package. Should I open an issue somewhere that it's not in the yaml?

No sorry. I switched the upstream url for that feedstock to github and that is why the bot no longer sees it as on pypi. This is expected. sorry for the trouble! I forgot about that test. Also, it'd be nice to separate the linter from this metadata generated by the bot, but that is another issue.

**Comment by BastianZim** [comment]
Ohhhh I see now that's a niche issue, interesting. 😄

Thank you!

**Pull request merged**
