### PR TITLE
Use travis-ci API 3

### PR DESCRIPTION
**Pull request by isuruf**
Should this go in a new maintenance branch 2.x, so that we can release this quickly?
Staged-recipes is broken atm.

### CODE REVIEW

**Comment by isuruf** [comment]
cc @conda-forge/core

**Comment by jakirkham** [comment]
Awesome! Thanks @isuruf.

Gave it a rough once over, but didn’t check whether it matched the Travis CI v3 API docs. Looks good though.

Were you able to test it at all? I know that’s pretty tricky. Just hoping to avoid a bug getting included in the release that we have to hot fix.

**Comment by isuruf** [comment]
> Were you able to test it at all? I know that’s pretty tricky. Just hoping to avoid a bug getting included in the release that we have to hot fix.

Only thing I didn't check is that the secure variable thing works.

**Comment by jakirkham** [comment]
Yeah, that's kind of a hard case to test. Sounds like good enough testing to me. If you are ready, please feel free to merge.

**Comment by isuruf** [comment]
I just checked that the old API and the new one gave the same response.

**Comment by jakirkham** [comment]
As to backporting it, would go ahead an open a new PR cherry-picking this commit and send it to the `2.x` branch instead. Not sure if other things might need to be cherry-picked, but am happy to defer to your judgement there.

**Comment by isuruf** [comment]
Looks like staged-recipes doing fine now. I'll backport it if there's any need.

**Comment by jakirkham** [comment]
Yeah it's probably not worth the trouble with 3.0.0 right around the corner.

**Pull request merged**
