### PR TITLE
Fix sorting of variants with zip_keys

### PR DESCRIPTION
**Pull request by isuruf**
Fixes https://github.com/conda-forge/conda-smithy/issues/790

### CODE REVIEW

**Comment by scopatz** [comment]
I don't really understand the error message on CI

**Comment by mbargull** [comment]
> I don't really understand the error message on CI

Likely, [mea culpa](https://github.com/conda-forge/conda-smithy/pull/800#issuecomment-396215434) which @isuruf [already fixed](https://github.com/conda/conda-build/pull/2949). The tests should work with `conda-build <3.10.6|>3.10.7` (i.e., after a `conda-build 3.10.8` is released).

**Comment by sodre** [comment]
Does this also fix sorting for variants outside of zip_keys? For example, in [go-feedstock](https://github.com/sodre/go-feedstock/blob/13f23b4fcbf623ab741d90954afbc3b4f6cfe600/recipe/conda_build_config.yaml#L7-L15)
```yaml
...
conda_goplatform:
  - linux-64
  - osx-64
  - win-64
conda_gofile:
  - ELF
  - Mach-O
  - PE32+
zip_keys:
...
```
The order of conda_goplatform must be the same as in conda_gofile.

**Comment by isuruf** [comment]
What do you mean? `conda_goplatform` and `conda_gofile` are variant keys found in a zip_keys and this PR is fixes that. `go-feedstock` was the example I used for writing this PR.

**Comment by sodre** [comment]
... running tests now...

**Comment by sodre** [comment]
conda-build 3.10.8 + conda-smithy@isuruf/sort2 works perfectly for me!

Is this ready to merge now, or do we need to (re)trigger Travis-CI?

**Comment by isuruf** [comment]
One test is failing because of an issue in conda-build for python 2.7. Can you send a PR to mark that test as xfail on python 2.7?

**Comment by mbargull** [comment]
Re. test failures on PY2: https://github.com/conda/conda-build/pull/2970.

**Comment by isuruf** [comment]
Tests pass now. Ready for review

**Pull request merged**
