### PR TITLE
Use platform name for the matrix

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by jakirkham** [comment]
Seems pretty sensible to me. Would you mind refreshing the test feedstock in the testing code?

**Comment by isuruf** [comment]
@jakirkham, what do you mean?

**Comment by isuruf** [comment]
@msarahan, what's the use of that test feedstock? Tests pass without the change.

**Comment by msarahan** [comment]
the test feedstock is used to make sure that rerendering works.  It is in a state as committed that doesn't match a later specified state.  We verify each of those states.

That particular line probably isn't something we check, and can be ignored.

**Comment by jakirkham** [comment]
Sorry, yes, I mean the feedstock we embed in the `conda-smithy` test code.

**Pull request merged**
