### PR TITLE
Test re-rendering is run in a feedstock

### PR DESCRIPTION
**Pull request by jakirkham**
Make sure that `conda-forge.yml` exists in the current working directory before re-rendering. If it does not exist, raise a `RuntimeError`.

Checklist
* [x] Added a ``news`` entry

### CODE REVIEW

**Comment by isuruf** [comment]
There's a warning at https://github.com/conda-forge/conda-smithy/blob/6d30530d5fa9f2d4f132e479b4aa5286ec93fb8e/conda_smithy/configure_feedstock.py#L1358 . Why is that not enough?

**Comment by jakirkham** [comment]
That does not appear to be sufficient. People still wind up re-rendering in the wrong directory and committing files. ( https://github.com/conda-forge/bottleneck-feedstock/pull/24 )

**Comment by isuruf** [comment]
This is a breaking change. If you want, you can check that the current folder has a `meta.yaml` there and error out.

**Comment by jakirkham** [comment]
I don't follow why the current behavior is expected. Please clarify.

**Comment by isuruf** [comment]
There are some external feedstocks without `conda-forge.yml` and just uses the default options. With this PR, they can't be rerendered.

**Comment by jakirkham** [comment]
Ok, thanks for clarifying. What if we ensure any empty `conda-forge.yml` always exists?

**Comment by isuruf** [comment]
I'd prefer if we linted the recipe in conda-forge to avoid suddenly breaking other people's workflow without a deprecation.

**Comment by isuruf** [comment]
Or make this a deprecation warning for a few months and then make it an error.

**Comment by jakirkham** [comment]
It looks like we are always generating `conda-forge.yml`.

https://github.com/conda-forge/conda-smithy/blob/67ff2285fd928197bcb71a02559ff23143ccebd8/conda_smithy/cli.py#L44-L47

**Comment by isuruf** [comment]
That's only for when generating a feedstock from staged-recipes.

**Comment by jakirkham** [comment]
Nope. That's every time `conda smithy init` is run.

**Comment by isuruf** [comment]
True, but it has not been a requirement to run `conda smithy init` to use `conda-smithy`. Please add a deprecation notice make it an error later.

**Comment by jakirkham** [comment]
I don't understand that statement. This has been the intended workflow from day one.

ref: https://github.com/conda-forge/conda-smithy#making-a-new-feedstock

**Comment by isuruf** [comment]
Okay. Can you add a more helpful error message about what to do then?

**Comment by jakirkham** [comment]
Sure. What would you propose?

**Comment by isuruf** [comment]
If the `forge_dir` is the intended feedstock root, add an empty `conda-forge.yml` and if not rerender from the feedstock root.

**Comment by jakirkham** [comment]
Thanks @isuruf! 😄

**Pull request merged**
