### PR TITLE
ruamel v0.16 fix

### LINKED ISSUE #1139: Not compatible with ruamel.yaml 0.16
Fails with,

```
Traceback (most recent call last):

  File "/home/travis/miniconda/bin/conda-smithy", line 10, in <module>

    sys.exit(main())

  File "/home/travis/miniconda/lib/python3.7/site-packages/conda_smithy/cli.py", line 470, in main

    args.subcommand_func(args)

  File "/home/travis/miniconda/lib/python3.7/site-packages/conda_smithy/cli.py", line 217, in __call__

    args.feedstock_directory, owner, repo

  File "/home/travis/miniconda/lib/python3.7/site-packages/conda_smithy/ci_register.py", line 351, in travis_token_update_conda_forge_config

    ] = travis_encrypt_binstar_token(slug, item)

  File "/home/travis/miniconda/lib/python3.7/contextlib.py", line 119, in __exit__

    next(self.gen)

  File "/home/travis/miniconda/lib/python3.7/site-packages/conda_smithy/utils.py", line 92, in update_conda_forge_config

    fh.write(yaml.dump(code))

  File "/home/travis/miniconda/lib/python3.7/site-packages/ruamel/yaml/main.py", line 448, in dump

    raise TypeError('Need a stream argument when not dumping from context manager')

TypeError: Need a stream argument when not dumping from context manager
```

cc @ocefpaf, @scopatz

### PR DESCRIPTION
**Pull request by scopatz**
Checklist
* [x] Added a ``news`` entry

closes #1139

### CODE REVIEW

**Comment by scopatz** [comment]
Also see https://yaml.readthedocs.io/en/latest/api.html#departure-from-previous-api

**Comment by CJ-Wright** [comment]
Should we have a try except for old versions of `ruamel.yaml`? Or should we pin the `ruamel.yaml` version?

**Comment by scopatz** [comment]
I think we should just pin

**Comment by bgruening** [comment]
@scopatz can you guide me on how to proceed here? bump the version of of the code and pin the ruamel.yaml in the meta.yaml file?

**Comment by sodre** [comment]
I think conda-smithy uses `rever` for new versions, it is on the readme.md.

**Comment by CJ-Wright** [comment]
The process would be to cut a release with `rever` via `rever x.y.z` where x.y.z is the new version number. Then once the release has issued a PR into the feedstock, update the ruamel.yaml pin.

**Comment by ocefpaf** [comment]
Thanks @scopatz! Merging this.

> The process would be to cut a release with `rever` via `rever x.y.z` where x.y.z is the new version number. Then once the release has issued a PR into the feedstock, update the ruamel.yaml pin.

I can do that in a minute.

**Pull request merged**
