### PR TITLE
Use D: for Windows installations on Azure

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [x] Added a ``news`` entry
* [x] Regenerated schema JSON if schema altered (`python conda_smithy/schema.py`)

The D: drive is supposed to be faster, so let's see if that's true!

### CODE REVIEW

**Comment by wolfv** [comment]
Can we also run builds and all on `D:/`? E.g. `set CONDA_BLD=D:/bld`?

**Comment by jaimergp** [comment]
That's already the case :D See `TEST END: D:\bld\win-64\nsis-3.10-h9ead6bc_log_0.conda` from https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1045477&view=logs&j=b0f7521e-dadf-5339-5101-26345e949aac&t=8017811c-a576-520e-3ed1-402a7f560f6d.

**Comment by jaimergp** [comment]
Hm, I feared as much. Maybe this should be configurable. I doubt most feedstocks are running out of space, but for sure all of them are installing the same base environment. We can shave a few minutes of those with D: + micromamba. 

As long as this is documented next to the "free_disk_space" options I think we should be fine, wdyt? If that's agreeable, then I'll put some settings.

**Comment by isuruf** [comment]
Yeah, that makes sense. The only issue here would be that feedstocks that customized CONDA_BLD_PATH to C: now has to customize MINIFORGE_HOME too. Maybe we do that in a migrator first?

**Comment by jaimergp** [comment]
There are only 14 of them, [according to the search](https://github.com/search?q=org%3Aconda-forge+CONDA_BLD_PATH+path%3Aconda-forge.yml&ref=opensearch&type=code). Could be faster to just send them manually, and I'm happy to do so :D

**Comment by isuruf** [comment]
Thanks Note that those feedstocks are the heaviest loads, so keep an eye on the CI if you can.

**Comment by jaimergp** [comment]
If only Azure respected the `[skip ci]` stuff :( We can cancel the runs on Azure, but I don't have admin permissions there, so if you see it's a problem, please feel free to cancel the heaviest ones as you see fit! Thanks and sorry!

**Comment by beckermr** [comment]
We should add short circuit skips based on the commit message to the azure templates.

**Comment by jaimergp** [comment]
See https://github.com/conda-forge/conda-smithy/pull/2077

**Comment by jaimergp** [comment]
> There are only 14 of them, [according to the search](https://github.com/search?q=org%3Aconda-forge+CONDA_BLD_PATH+path%3Aconda-forge.yml&ref=opensearch&type=code).

There we go:

- [ ] https://github.com/conda-forge/descarteslabs-feedstock/pull/73
- [ ] https://github.com/conda-forge/scipy-feedstock/pull/286
- [ ] https://github.com/conda-forge/intel-compiler-repack-feedstock/pull/50
- [ ] https://github.com/conda-forge/google-cloud-cpp-feedstock/pull/186
- [ ] https://github.com/conda-forge/flang-feedstock/pull/75
- [ ] https://github.com/conda-forge/deno-feedstock/pull/137
- [ ] https://github.com/conda-forge/occt-feedstock/pull/117
- [ ] https://github.com/conda-forge/onnxruntime-feedstock/pull/133
- [ ] https://github.com/conda-forge/qt-main-feedstock/pull/297
- [ ] https://github.com/conda-forge/lancedb-feedstock/pull/21
- [ ] https://github.com/conda-forge/qt-webengine-feedstock/pull/66
- [ ] https://github.com/conda-forge/qgis-feedstock/pull/465

**Comment by jakirkham** [comment]
FWIW in PR ( https://github.com/conda-forge/conda-smithy/pull/1966 ) has switched to using PowerShell to download Miniforge, which helped a little bit. Though the main push of that PR was to free more space on the image (as space is a constant challenge). Also please see issue ( https://github.com/conda-forge/conda-smithy/issues/1949 ) about space limitations

**Comment by jaimergp** [comment]
> FWIW in PR ( https://github.com/conda-forge/conda-smithy/pull/1966 ) has switched to using PowerShell to download Miniforge, which helped a little bit.

I think PowerShell has a non-negligible start time, right? We can compare against the `certutil` hack though. The important bit is to have it in the bat script though; the download tool itself is not as important.

**Comment by jakirkham** [comment]
I don't think so. The download was pretty fast IIRC

In any event we are currently calling Python to do that download, which has its own startup time

Also not sure what kind of security measures are applied on Azure. Depending on what they are, these can add overhead to startup, runtime, downloads, etc.

If we are especially concerned with startup time, we could use Batch for downloading. The syntax is a little unpleasant. Though hopefully it is write once

If the goal here is just generally to improve CI startup time, it might be worth revisiting Windows Docker images ( https://github.com/conda-forge/docker-images/pull/209 ). With that we could do all of the download, configuration, etc. in the image. If Azure has a particular registry it likes, we could also push to that registry for faster downloading (and maybe opt-in to earlier scanning to avoid this cost in CI jobs)

**Comment by jaimergp** [comment]
> I don't think so. The end-to-end time of the PowerShell download was pretty fast
> 
> In any event we are currently calling Python to do that download, which has its own startup time
> 
> Also not sure what kind of security measures are applied on Azure. Depending on what they are, these can add overhead to startup, runtime, downloads, etc.
> 
> If we are especially concerned with startup time, we could use Batch for downloading. The syntax is a little unpleasant. Though hopefully it is write once

Yea, using `certutil` is not that bad: https://github.com/conda-forge/conda-smithy/pull/2075/files#diff-69e88e5a41c617697582fa7d0b6a32d712995f682e7cac24b517d4b8cc4ff9b8R28

**Comment by jakirkham** [comment]
> Yea, using `certutil` is not that bad: https://github.com/conda-forge/conda-smithy/pull/2075/files#diff-69e88e5a41c617697582fa7d0b6a32d712995f682e7cac24b517d4b8cc4ff9b8R28

That looks nice! I would be happy with that 😄

**Review by beckermr — APPROVED** [review]

**Comment by beckermr** [comment]
Shall we merge @conda-forge/core?

**Comment by jakirkham** [comment]
Honestly am a little nervous about the disk space usage discussion above. Mention this as we are running into low memory warnings on Windows more frequently ( for example: https://github.com/conda-forge/numpy-feedstock/issues/334 ). So would like to better understand how changing the default drive will affect this (given a swapfile may be in use)

**Comment by beckermr** [comment]
@jakirkham in your estimation is numpy a typical build or more on the extreme end of things?

I was hoping that for more pedestrian builds, we'd be just fine.

**Comment by jakirkham** [comment]
My impression is NumPy is pretty low in resource usage (though I could always be missing something like a problematic test)

Certainly higher resource usage feedstocks are seeing this warning too

**Comment by wolfv** [comment]
How about we add a knowledge base entry on how to change this when you encounter these warnings?

**Comment by beckermr** [comment]
The docs will update from the JSON schema but we could add more useful text for sure. 

I am surprised we consider numpy "low" on resource usage when building. The numpy windows builds run for ~25 minutes and include 5 minutes of testing. That seems high to me compared to a more typical 5 or 10 minute build.

**Comment by jakirkham** [comment]
For a compiled build, yes I would say the lower end. NumPy is C only (a little Cython) with a pretty simple test suite. No C++

Personally would consider high to be something like PyTorch where we just need a different CI provider altogether. We have quite a few things like

Perhaps you can share your definition?

**Comment by beckermr** [comment]
I don't have one and so am happy with whatever. I am surprised but I guess this is how it is. So should we merge or wait?

**Comment by jaimergp** [comment]
Worst thing that can happen is that folks will experience disk issues, we'll hear about it in the Element room, and we will flip the default so we keep installing to `C:` even if slower. But that's hypothetical and maybe it's not that bad. Low memory is not necessarily low disk even with swaps considered. I'd say let's merge and see?

**Comment by h-vetinari** [comment]
> Honestly am a little nervous about the disk space usage discussion above. Mention this as we are running into low memory warnings on Windows more frequently

The disk space situation is independent from potential memory shortage (well, except in the most extreme builds where we manually set up a swapfile to use some diskspace to boost too-low memory and end up nearly running out of both, but that's neither common, nor the case of numpy).

**Comment by jaimergp** [comment]
There are [some docs](https://github.com/conda-forge/conda-smithy/pull/2076/files#diff-03c73cc900d31f00e1bae4e15723846d6bcd89b046723cd7500a57b23b41222eR220-R231) in the schema already, and those will show up [in this page](https://conda-forge.org/docs/maintainer/conda_forge_yml/#azure) (although that's a bit hidden under `AzureConfig` foldable), so the search engine will pick it up at some point.

We can additionally set up a KB entry if we feel that's necessary. I'm inclined to do so when we start working on this [new suggestion for Dev Drives](https://github.com/conda-forge/conda-smithy/issues/2095).

**Comment by jaimergp** [comment]
To whomever merges this, consider checking / merging the equivalent PR for staged-recipes: https://github.com/conda-forge/staged-recipes/pull/27767 🙏

**Comment by beckermr** [comment]
I think we have enough consensus to merge. Once we release if we are seeing a lot of issues we can make adjustments.

**Pull request merged**
