### PR TITLE
fix: remove lint for changes to staged-recipes example

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [x] Added a ``news`` entry
* [x] Regenerated schema JSON if schema altered (`python conda_smithy/schema.py`)

closes #2036

### CODE REVIEW

**Comment by beckermr** [comment]
@jaimergp @isuruf This is ready for review!

**Comment by beckermr** [comment]
Any comments here @conda-forge/core?

**Review by xhochy — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks Matt! 🙏

So where is this linting done in `staged-recipes`? Is there a PR somewhere with those changes?

**Comment by beckermr** [comment]
here: https://github.com/conda-forge/staged-recipes/blob/main/.github/workflows/do_not_edit_example.yml

**Comment by jakirkham** [comment]
Thanks Matt! 🙏

Sorry forgot we added this a while back 🤦‍♂️

Am glad you remembered (and well enough to clean up this last bit)

**Comment by beckermr** [comment]
It was @isuruf who deserves credit for remembering!

**Pull request merged**
