### PR TITLE
Azure: osx forward env vars set by conda-forge-ci-setup

### PR DESCRIPTION
**Pull request by mariusvniekerk**
Rework osx azure build to `conda activate base` at every step.
I've also updated how we get conda as the official approach outlined in the documentation works now.

Checklist
* [ ] Added a ``news`` entry

### CODE REVIEW

**Comment by isuruf** [comment]
Here's an alternative. https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/48
For this to work, we need to activate the conda environment in each task instead of adding to PATH. (which should be done regardless anyway)

**Comment by isuruf** [comment]
Can you change this PR to activate the miniconda environments in linux, osx, windows? (There's no need to do hacks like https://github.com/conda-forge/conda-forge-ci-setup-feedstock/commit/2846d2ddc456743a78d52386499639431c580626 if this is done)

**Comment by isuruf** [comment]
And also revert https://github.com/conda-forge/conda-smithy/pull/1016/files

**Comment by mariusvniekerk** [comment]
well probably not linux since thats inside container land so its already activated.

**Comment by isuruf** [comment]
Ah, yes. No need for linux

**Comment by isuruf** [comment]
Do you have a test PR to show that this works? If so, +1 to merge

**Comment by mariusvniekerk** [comment]
I'll apply it to the thrift-cpp one we've been using for tests quickly

**Comment by mariusvniekerk** [comment]
sample test run here. https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=18261
Do you have an example feedstock that had issues with the osx build root?

**Comment by isuruf** [comment]
https://github.com/conda-forge/tbb-feedstock/pull/46

**Comment by mariusvniekerk** [comment]
Build for tbb: https://github.com/conda-forge/tbb-feedstock/pull/47/checks?check_run_id=71417946

**Comment by mariusvniekerk** [comment]
Looks like it works?  tbb is still failing on azure, but probably for other reason

**Pull request merged**
