### PR TITLE
Fix regenerate rerender

### PR DESCRIPTION
**Pull request by ocefpaf**
I am not sure if we should fix this or just remove that comment. We don't have that comment in the other templates.

### CODE REVIEW

**Comment by janschulz** [comment]
It's not wrong: rerender is an alias for regenerate https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/cli.py#L169-L171 but using rerender does not work on py27: https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/cli.py#L56

**Comment by jakirkham** [comment]
Really? I've used `rerender` with Python 2.7. Why shouldn't it work?

**Comment by jakirkham** [comment]
> We don't have that comment in the other templates.

Actually, we do. See this [line]( https://github.com/conda-forge/conda-smithy/blob/9cd7e42428c4621039366b023a19c1eba5214954/conda_smithy/templates/run_docker_build.tmpl#L4 ). Basically, it is to stop people from mucking with the autogenerated files. I don't know how well it works in practice. In any event, I'm in favor of the proposed change as it seems `rerender` is the common syntax now.

**Comment by pelson** [comment]
:+1: on this. I'll merge once we have got closer to the release.

**Comment by janschulz** [comment]
> Really? I've used rerender with Python 2.7. Why shouldn't it work?

See the source: https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/cli.py#L56 if it works, I have no clue how it is made available :-)

**Comment by janschulz** [comment]
Ok, i take that back: there is another py2 Workaround further down, which makes the command available...

**Comment by pelson** [comment]
https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/cli.py#L219

**Comment by pelson** [comment]
"A poor-man's alias for regenerate."

**Pull request merged**
