### PR TITLE
CLI changes, switch to conda-build-all, bugfixes

### PR DESCRIPTION
**Pull request by janschulz**
This is https://github.com/conda-forge/conda-smithy/pull/51 without the multi part.

Includes:

* The CI services now use `conda buildall` for the builds, which leads to a much easier CI-Support templates
* renames `conda smithy register-feedstock-ci` to `conda smithy register-ci`
* renames `conda smithy github-create`to `conda smithy register-github` 
* lots of additions to the help strings for the command line switches
* A fix for creating a working version of the docker script when using init on windows 
* A fix for registering the CI tokens (not all were added to the CI scripts) 
* Added a message to each command which tells you what to do next
* Added error messages how to get the required tokens and where to put them
* Added a configuration for the github settings (username + repo name) which enables the generation of proper links to the CI services.
* add the possibility to influence the matrix conditions (e.g. to remove py2.7 builds)

**Todo**:

* [x] how to prevent 2.6 builds? I think this needs an additional parameter to `conda buildall` and this should be configurable via `conda-forge.yml`.
* [x] ~~Investigate why mac fails. I've actually no clue :-( Fails with ["conda.resolve.NoPackagesFound: No packages found in current osx-64 channels matching: python"](https://travis-ci.org/JanSchulz/example-package-feedstock/builds/107505689)~~ this seems to be not failing anymore, although I have no idea why...

Please test, I only ran the regeneration part and that produced a diff compared to the (tested) multi PR which seemed ok (removed mentions of "one or more recipes").

Closes: https://github.com/conda-forge/conda-smithy/issues/50

### CODE REVIEW

**Comment by JanSchulz** [comment]
Rebased on top of the latest release... 

Sorry that this is again big, but apart form the small commits at the beginning, I can't see how to split the big change in the last commit :-/

I would appreciate if you could give this a stern look and maybe a merge before changing things in the rest of the codebase, as this was (and probably is) a mess to rebase :-/ Thanks! :-)

**Comment by JanSchulz** [comment]
BTW: this still has the problem that it breaks on mac os x :-(

-> https://travis-ci.org/JanSchulz/example-package-feedstock

It also builds 2.6 packages, I currently do not understand the `conda-build-all` internals to prevent that.

**Comment by JanSchulz** [comment]
> Just to re-iterate - there are some great changes in here - but the PR is just too broad in scope. Things like pulling out the use of BINSTAR_TOKEN will be hugely valuable, and I'm keen for them to be done in small PRs where possible (in this case, I believe there are several completely independent improvements).

Ok, how should I do this. Yesterday I spent about 3-4 hours to separate the multi PR into two independent PRs: this PR "without any Multi" and the other one ("multi only" #58). 

This PR has hopefully independent buildable commits but I can't guarantee this. I would be ok to submit the commits of this PR individually but I kind of dread this as this means that each change will again mean a horrible rebase marathon in all other PRs. Would it be ok to take this PR in one go and do the review either also in one go or in the individual commits + add commits on top of this PR?

**Comment by pelson** [comment]
> Yesterday I spent about 3-4 hours to separate the multi PR into two independent PRs

Ouch. Let me see whether I can review this commit by commit. Inevitably we will hit a point where there are review actions, and I wont be able to go any further (the advantage of separate PRs), but I don't want you to have to go through another rebase marathon.

**Comment by JanSchulz** [comment]
>  (the advantage of separate PRs)

yep... Thanks for doing the review in this PR. Let's see how far we can get...

Unfortunately, this PR started as a multi PR and then started to accumulate all kinds of bugfixes and so on :-( On the other hand: the final multi commit is now actually a really straightforward one :-)

**Comment by JanSchulz** [comment]
Updated with the comments from https://github.com/conda-forge/conda-smithy/pull/58

**Comment by JanSchulz** [comment]
And now it's possible to prevent the py2.6 builds, so we are on par with the old implementation.

**Comment by pelson** [comment]
Many of the excellent ideas from this PR were pulled in. The major blocking point was the many-recipes.
Since this has now gone stale, and we have reached the point of ruling out multiple-recipe feedstocks for the time being, I'm going to close this.

Thanks for taking the time to put this together @janschulz, and in particular for splitting off many of the parts into separate PRs.

**Pull request closed without merging**
