### PR TITLE
Add BSD-3-Clause-Modification

### PR DESCRIPTION
**Pull request by BastianZim**
Checklist
* [ ] Added a ``news`` entry

### CODE REVIEW

**Comment by jakirkham** [comment]
What was the original motivation? Just trying to get more context on the issue 🙂

**Comment by BastianZim** [comment]
It was required for https://github.com/conda-forge/staged-recipes/pull/18080 but since a new release here would be required I think it makes more sense to focus on creating the separate packages that was discussed in gitter.

Also, I downloaded a file containing all current SPDX licenses and will make a PR with that instead until then.

**Comment by isuruf** [comment]
@BastianZim, I'm about to do a new release. If you can send that PR today, we can get that in for the new release.

**Comment by BastianZim** [comment]
Ok give me ~1h as I'm currently out. I'll ping you.

**Pull request closed without merging**
