### PR TITLE
Workaround for 32-bit issue

### PR DESCRIPTION
**Pull request by isuruf**
Fixes https://github.com/conda-forge/conda-smithy/issues/734 with a hack. cc @msarahan

### CODE REVIEW

**Comment by msarahan** [comment]
Thanks for sorting this out.  This seems like a good workaround to me.

**Comment by jakirkham** [comment]
Seems fine to me too. Have you tested it somewhere?

**Comment by isuruf** [comment]
https://ci.appveyor.com/project/isuruf/boost-cpp-feedstock/build/1.0.31

**Comment by jakirkham** [comment]
Looks great. Feel free to merge. Thanks.

**Pull request merged**
