### PR TITLE
Add a reminder of how to get the bot to rerender a feedstock.

### PR DESCRIPTION
**Pull request by jasongrout**

### CODE REVIEW

**Comment by ocefpaf** [comment]
Thanks! That is better!!

**Comment by ocefpaf** [comment]
> Note that this would trigger a rerender. Was that intended?

Yeah... Not really though. We need to find a way to write that message and not trigger the re-rendering :-/

**Comment by dougalsutherland** [comment]
Hmm. Mentions aren't rendered inside code blocks, like I can say `@conda-forge/core` all I want and you don't get pinged, but the bot doesn't parse that. Should it?

**Comment by jasongrout** [comment]
I put it in backticks so that it wouldn't trigger the bot, but I didn't test it. I think the bot shouldn't recognize mentions in `<code>`.

**Comment by jasongrout** [comment]
The other thing we could do is put it in the HTML comment of the template, so it's easy to copy/paste when creating a new issue (do the html comments become part of the text?).

**Comment by dougalsutherland** [comment]
It seems like it's actually okay, the webhook isn't called if the bot isn't actually pinged: https://github.com/conda-forge/rxcpp-feedstock/issues/3. If the bot is otherwise pinged in the comment, though, it'll see the `please rerender` command and do it; it doesn't know not to parse commands inside backticks.

**Comment by jakirkham** [comment]
Interesting, that's actually a bit surprising to me. Do we actually check that the bot was pinged somewhere?

**Comment by dougalsutherland** [comment]
I think it's just that the hook only gets called when it's pinged? I'm not sure; I guess it could have been something else going wrong there, though there's not a related error in the logs.

**Comment by isuruf** [comment]
We don't check that the bot is pinged

**Comment by isuruf** [comment]
So, what do we do? revert until a fix is implemented?

**Comment by jakirkham** [comment]
Don’t think this is a problem. Tested in an issue and it seemed ok. Though feel free to test and/or investigate further.

**Comment by jakirkham** [comment]
Just now saw PR ( https://github.com/conda-forge/conda-smithy/pull/858 ). Seems like a nice layer of protection against unnecessary re-renderings.

**Pull request merged**
