### PR TITLE
Switched to using Miniforge to setup CI environment in Azure

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [x] Added a ``news`` entry

cc @wolfv

### CODE REVIEW

**Comment by isuruf** [comment]
@BastianZim, can you check this PR too?

**Review by BastianZim — APPROVED** [review]
Nice! I’m not at my computer right now but I can test it in ~2h.

**Comment by wolfv** [comment]
awesome. looks great.

**Comment by isuruf** [comment]
Works fine on https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=514029&view=logs&j=5be07ae1-d8ba-5406-47b6-8e3a3a12f825&t=c94d5231-acfc-5e67-dafc-77bdd383ead4

**Comment by isuruf** [comment]
@hmaarrfk, thoughts?

**Comment by hmaarrfk** [comment]
This is very welcome!

**Review by hmaarrfk — APPROVED** [review]

**Comment by h-vetinari** [comment]
I'm seeing resolution errors on windows in https://github.com/conda-forge/numpy-feedstock/pull/272 during the "Install conda-build" phase that was changed here. Not sure what's causing it TBH.

**Comment by BastianZim** [comment]
You’re still using the old setup. Rerendering should hopefully fix that.

**Comment by h-vetinari** [comment]
> You’re still using the old setup. Rerendering should hopefully fix that.

Interesting that this breaks unrerendered recipes, but duh, yes, I should have thought of that. Thanks!

**Pull request merged**
