### PR TITLE
Allow custom branch in repo for badges

### PR DESCRIPTION
**Pull request by hmaarrfk**
For a project of mine, I'm trying to stay close to the upstream conda-forge-feedstock, but would prefer to have the badges generated for my own branch.

Does this do what I want it to do?

Do I need to add something around these lines of code:
https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/github.py#L99

### CODE REVIEW

**Comment by jakirkham** [comment]
LGTM. Were you able to try it out?

**Comment by shadowwalkersb** [comment]
Is this related to #318, by any chance?

**Comment by hmaarrfk** [comment]
I would need to figure out how to install and test my spin of smithy. Maybe
I can just clobber my old install with these files.

Seems like #318 could be helped by this. I think he wants the branch name
to be read from git or smithy rerender automatically. Which may be
problematic with the fork/PR model.

**Comment by jakirkham** [comment]
This is what I do to accomplish this. Maybe we should add it to the docs in another PR if it works ok for you.

```bash
conda activate
conda remove -y conda-smithy
conda install -y pip  # if `pip` isn't in `base`
pip install --no-deps -e <path to conda-smithy git repo> 
```

**Comment by hmaarrfk** [comment]
@isuruf did you happen to test the patch?

**Pull request merged**
