### PR TITLE
Mark patch files as binary

### PR DESCRIPTION
**Pull request by isuruf**
This is so that patch files are not messed up by git

### CODE REVIEW

**Comment by jakirkham** [comment]
Should we add `.diff` too?

**Comment by isuruf** [comment]
Yes, that's a good idea

**Comment by jakirkham** [comment]
IIUC the issue is with CRLF files that git is normalizing to LF, correct? While these patches are technically broken, I don't see an obvious way around it if the code being patched is using CRLF. So am ok with this solution.

**Comment by jakirkham** [comment]
cc @mingwandroid

**Comment by isuruf** [comment]
> IIUC the issue is with CRLF files that git is normalizing to LF, correct? 

yes

**Comment by jakirkham** [comment]
Thanks @isuruf.

**Comment by synapticarbors** [comment]
Should the same change be made to `staged-recipes`:

https://github.com/conda-forge/staged-recipes/blob/master/.gitattributes

**Comment by jakirkham** [comment]
Yes. Please feel free to add it.

**Comment by jakirkham** [comment]
Should add this fixed issue ( https://github.com/conda-forge/conda-smithy/issues/549 ).

**Pull request merged**
