### PR TITLE
choco on azure

### PR DESCRIPTION
**Pull request by scopatz**
Checklist
* [x] Added a ``news`` entry

This is needed to get cudatoolkit working on Windows. https://github.com/conda-forge/cudatoolkit-feedstock/pull/7 CC @conda-forge/cudatoolkit

### CODE REVIEW

**Review by beckermr — COMMENTED** [review]
I have one. comment on the API. Do we want to use the conda-forge.yml or do we want to do something similar to yum where the packages are listed in a file in the feedstock?

**Comment by scopatz** [comment]
I really didn't want to add another file to read in.

**Comment by scopatz** [comment]
The yum-requires is kind of an old hack in my opinion, that comes from before conda-smithy and rerendering were as established as they are now

**Comment by beckermr** [comment]
> I really didn't want to add another file to read in.

Totally reasonable. Do we have a good way of enabling this on staged-recipes if it is in the conda-forge.yml? I know that is a weird case, but it might be useful.

**Comment by scopatz** [comment]
Right, so there is no way to add this to staged-recipes. Also, in my opinion, conda-smithy should have a way of rendering a staged-recipes type of repo (but that is well beyond the scope of this PR).

**Comment by beckermr** [comment]
OK. I am 100% fine with the PR as is, but I did want to make sure I understood what the limitations were. Thanks!

**Comment by scopatz** [comment]
Still doing some testing with the actual feedstock.

**Comment by scopatz** [comment]
Here is the commit where it rendered correctly: https://github.com/conda-forge/cudatoolkit-feedstock/pull/7/commits/8d51d248cee9cba2b4d067f9afda5b38514674a6 

So I think this is good from my end. Ready for review @conda-forge/conda-smithy!

**Comment by isuruf** [comment]
Have you rerendered a separate feedstock to see if this changes other feedstocks? (Maybe add extra spaces)

**Comment by scopatz** [comment]
@isuruf - yes, I checked on glib, and it does not seem to add any extra space.  I am pretty sure I used the proper `-` in the template, but please feel free to double check.

**Comment by isuruf** [comment]
Please add documentation for this new parameter: https://conda-forge.org/docs/maintainer/conda_forge_yml.html

**Comment by jakirkham** [comment]
Thanks Anthony! 😄

**Comment by scopatz** [comment]
NP! Docs available in https://github.com/conda-forge/conda-forge.github.io/pull/1172

**Review by beckermr — APPROVED** [review]

**Pull request merged**
