### PR TITLE
Honor channels -> sources in appveyor

### PR DESCRIPTION
**Pull request by janschulz**
Up to now the conda-forge channel was hardcoded...

Fixes: https://github.com/conda-forge/conda-smithy/issues/178

### CODE REVIEW

**Comment by pelson** [comment]
:+1:

Did you check that the whitespace is behaving as expected? I'm keen not to add whitespace noise to all >500 feedstocks unnecessarily.

**Comment by janschulz** [comment]
Will check and report back...

**Comment by janschulz** [comment]
Ok, there were problems, good catch! I changed the template so that whitespace changes are not happening with the default config (conda-forge only) and it's also not producing additional empty lines for the rest

**Comment by janschulz** [comment]
BTW: is this code still needed:

```
class MatrixCaseEnvVar(object):
    def __init__(self, name, value):
        self.name = name
        self.value = value

    def __iter__(self):
        # We make the Var iterable so that loops like
        # ``for name, value in cases`` can be used.
        return iter([self.name, self.value])

    def __cmp__(self, other):
        # Implement ordering so that sorting functions as expected.
        if not isinstance(other, type(self)):
            return -3
        elif other.name != self.name:
            return -2
        else:
            return cmp(self.value, other.value)
```

At least the sorting shouldn't work under py3 (pycharm shows an erro for `cmp` and according to http://python3porting.com/problems.html#unorderable-types-cmp-and-cmp  `__cmp__` is not used anymore...?

**Comment by pelson** [comment]
> BTW: is this code still needed:

I think it is, but let's leave it out of the discussion for this PR :wink: :smile: 

> I changed the template so that whitespace changes are not happening with the default config (conda-forge only)

Cool. Thanks @janschulz!

**Comment by pelson** [comment]
I'm merging this on the basis that it has no impact to already rendered feedstocks. Thanks @janschulz!

**Comment by janschulz** [comment]
> I think it is, but let's leave it out of the discussion for this PR :wink: :smile:

https://github.com/conda-forge/conda-smithy/issues/188

**Pull request merged**
