### PR TITLE
Allow conda-forge.yml to be empty

### PR DESCRIPTION
**Pull request by saraedum**
Otherwise, you'd get a `IndexError: list index out of range`.

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks!

**Comment by scopatz** [comment]
Can you please include a test for this case?

**Comment by saraedum** [comment]
It's not obvious to me how to do this. Are there any tests that take an entire repository tree as input?

**Comment by scopatz** [comment]
I thought there were, but you could also just test that function

**Comment by saraedum** [comment]
@scopatz, I added tests now. (Took a bit longer than I thought…)

**Pull request merged**
