### PR TITLE
fix: allow tests to run in conda-build

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [x] Added a ``news`` entry
* [x] Regenerated schema JSON if schema altered (`python conda_smithy/schema.py`)

### CODE REVIEW

**Comment by beckermr** [comment]
pre-commit.ci autofix

**Comment by beckermr** [comment]
pre-commit.ci autofix

**Comment by beckermr** [comment]
@conda-forge/core this one is ready for review!

**Comment by beckermr** [comment]
I tested this in this PR: https://github.com/conda-forge/conda-smithy-feedstock/pull/334

**Review by h-vetinari — APPROVED** [review]
👍 

Checked out https://github.com/conda-forge/conda-smithy-feedstock/pull/334 too.

**Pull request merged**
