### PR TITLE
add instructions on how to specify target channels to upload

### PR DESCRIPTION
**Pull request by shadowwalkersb**
I thought it would be quite useful to have these instructions. I had to figure them out by looking at the code and doing trial--and-error. Let me know if I need to update anything if you are interested in the PR.

### CODE REVIEW

**Comment by jakirkham** [comment]
I like the addition, but I don't like the location. Maybe we need it as a separate number or in a different/new section (feedstock management?) or similar.

**Comment by shadowwalkersb** [comment]
I don't have much to offer regarding the location.

**Comment by pelson** [comment]
I kind of think it fits OK with the line above (i.e. `--user github_user_name`). Not that I think either is the content I would want to see a new conda-forge feedstock maintainer having to go through - this is entirely for the non conda-forge usecase IMO.

@jakirkham - you have merge rights, and I'm 👍 . Please feel free to iterate/merge as you see fit.

**Comment by shadowwalkersb** [comment]
Here is how it looks.

screen shot 2016-09-03 at 11 33 34 am

**Comment by jakirkham** [comment]
Yep that looks good. Thanks @shadowwalkersb.

This might have introduced conflicts with PR ( https://github.com/conda-forge/conda-smithy/pull/286 ), but I guess there is one more thing we want to do there anyways.

**Pull request merged**
