### PR TITLE
add VERBOSE_AT and VERBOSE_CM to always recorded vars

### LINKED ISSUE #699: Mark VERBOSE_AT as always used.

### PR DESCRIPTION
**Pull request by msarahan**
fixes #699

### CODE REVIEW

**Comment by isuruf** [comment]
Looks like conda-smithy will record it if it is used. I don't how it detects that, but it works.

**Comment by msarahan** [comment]
It works with some more or less heinous regexes.  https://github.com/conda/conda-build/blob/master/conda_build/variants.py#L524-L527

Happy to close this if conda-build's functionality is adequate.

**Comment by isuruf** [comment]
Yes, that's enough. Thanks @msarahan

**Comment by jakirkham** [comment]
Interesting, thanks for exploring this all. :)

**Pull request closed without merging**
