### PR TITLE
Add mpi default value

### PR DESCRIPTION
**Pull request by davidbrochart**
Checklist
* [ ] Added a ``news`` entry

See https://github.com/conda-forge/conda-forge.github.io/pull/903

### CODE REVIEW

**Comment by davidbrochart** [comment]
Not sure the CI error is related, should we ignore it?

**Comment by CJ-Wright** [comment]
The CI failure is a different problem

**Comment by davidbrochart** [comment]
Good, should this PR be merged?

**Comment by CJ-Wright** [comment]
Let me ping core, I'm not as well versed in our mpi requirements. @conda-forge/core

**Comment by isuruf** [comment]
> Good, should this PR be merged?

We have to fix conda-smithy's tests first before merging this PR. You don't have to fix it in this PR, but this PR will have to wait.

**Comment by jakirkham** [comment]
Could someone please raise an issue about the test failure? We can discuss how to fix there.

**Pull request merged**
