### PR TITLE
Update Travis CI template

### LINKED ISSUE #1940: How to test updates to `.travis.yml`
### Comment:

I've been in touch with Travis CI Support regarding https://github.com/conda-forge/status/issues/178. In a recent email, they've suggested try changing:

- `language: generic` to `language: shell`
- `matrix.include` to `jobs.include`

to see if that makes any difference. How should I actually test these? I realize this could be a simple PR here, but seems like jumping the gun to update `conda-smithy` itself without evidence that these changes aren't superficial.

Should I test manually overwriting these (i.e., temporarily edit the `.travis.yml` without a rerender) in a draft PR on an affected repository?

### PR DESCRIPTION
**Pull request by mfansler**
Travis CI **linux-ppc64le** jobs are currently failing (https://github.com/conda-forge/status/issues/178). Travis support recommended updating the config (#1940). This PR implements those changes.

Checklist
* [x] Added a ``news`` entry

Closes #1940.
Should resolve https://github.com/conda-forge/status/issues/178.

### Testing
These changes have been tested in https://github.com/conda-forge/r-backbone-feedstock/pull/15. Some relevant documentation of the *partial* success (and previous failure):

- [full recent build history](https://app.travis-ci.com/github/conda-forge/r-backbone-feedstock/pull_requests?serverType=git)
- pre-update [example failure](https://app.travis-ci.com/github/conda-forge/r-backbone-feedstock/builds/270410159)
- post-update [example ppc64le-only passing](https://app.travis-ci.com/github/conda-forge/r-backbone-feedstock/builds/270680655?serverType=git)
- post-update [example partial passing](https://app.travis-ci.com/github/conda-forge/r-backbone-feedstock/builds/270682860?serverType=git) (1/2 ppc64le jobs ran on first try; restarted failed job led to proper start).

Also testing in https://github.com/conda-forge/r-pki-feedstock/pull/23. See [Travis CI jobs for the build](https://app.travis-ci.com/github/conda-forge/r-pki-feedstock/builds/270683890). Only 1/2 ppc64le jobs ran on first try. However, restarting individual failed job led to successful start on second try.

**Control Tests**
Just to make sure this wasn't a fluke of timing (maybe the changes weren't the cause?), I also restarted 4 failed jobs without the changes and they still all failed.

### Summary
These changes appear to only provide partial resolution. Half of the **linux-ppc64le** jobs pass, but that is a far better situation than 0% that has been the situation up to now. This seems like returning to the previous status quo where users may need to manually restart them.

I'd recommend we merge this since it at least appears to improve the situation.

### CODE REVIEW

**Comment by h-vetinari** [comment]
Since you report the changes to be working/effective, is there a reason this PR is still a draft?

**Comment by mfansler** [comment]
@h-vetinari thanks for having an eye out. I updated with the results. Seems like it doesn't fully resolve the situation, but it does at least get some jobs passing again.

**Review by h-vetinari — APPROVED** [review]
I've had massive issues with the Travis UI recently (cannot even access the CI logs without tedious workarounds), so any improvement here is welcome.

Thanks for reaching out to Travis support and this PR!

**Comment by jakirkham** [comment]
> I've had massive issues with the Travis UI recently (cannot even access the CI logs without tedious workarounds), so any improvement here is welcome.

Interesting. Have been dealing with the same issue for ~1 month now. Reported to Travis, but have no leads yet. Maybe they can find some similarities between our situations to narrow down the problem. Have you already reported this issue?

**Comment by h-vetinari** [comment]
> Have you already reported this issue?

No. I really have no confidence in Travis and spending any time on it makes my hair stand on end. I prefer to switch affected feedstocks to cross-compilation or emulation rather than dealing with Travis any more than absolutely necessary.

That's not to say that I don't welcome improvements there (hence kudos to @mfansler), but it's unlikely to be me pursuing these.

**Comment by jakirkham** [comment]
Understandable. Am taking the same approach at this point

**Pull request merged**
