### PR TITLE
Fix link to conda-smithy

### PR DESCRIPTION
**Pull request by rhattersley**

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks!

**Comment by pelson** [comment]
Thanks for the PR @rhattersley and @scopatz for merging. Go community :+1:

**Comment by rhattersley** [comment]
100:1 chat to content ratio. Go community :stuck_out_tongue_winking_eye:

**Comment by pelson** [comment]
Mighty oaks from little acorns grow. :wink: :v:

**Comment by rhattersley** [comment]
>> 100:1 chat to content ratio.

> Mighty oaks from little acorns grow. :wink: :v:

To be clear, I just meant this PR. I'm :+1: for the project as a whole.

**Pull request merged**
