### PR TITLE
Fix argument order for Travis

### PR DESCRIPTION
**Pull request by leofang**
Fix https://github.com/conda-forge/conda-forge.github.io/issues/1761.

Checklist
* [x] Added a ``news`` entry

### CODE REVIEW

**Comment by leofang** [comment]
@conda-forge/core This is ready for review. It'd be nice if we could release a new version after this is merged 🙂

**Comment by jakirkham** [comment]
Did we test this in a feedstock somewhere?

**Comment by leofang** [comment]
Already on it 🙂
https://github.com/conda-forge/cupy-feedstock/pull/169/commits/c08c9b85bbc6e3a5f8224416c488af131b6b1dd4
So far Travis does not complain, but there's no further CI log output, either, not sure if it silently fails, or is busy in the background...

**Comment by leofang** [comment]
OK I think this is the right fix. The CI test still failed, but not at the start time (when without the fix) but due to timeout or something when `idle_timeout_minutes` is not set (`aarch64-conda-linux-gnu-c++: fatal error: Killed signal terminated program cc1plus`).
https://app.travis-ci.com/github/conda-forge/cupy-feedstock/jobs/571557403

**Comment by leofang** [comment]
Though it's worth noting `travis_wait 120` does not help lengthen the CI time from 50 mins to 120 mins; the jobs are still killed within 50 mins... Perhaps it never worked?!

**Comment by leofang** [comment]
Another example of timeout: https://app.travis-ci.com/github/conda-forge/cupy-feedstock/jobs/571557408

**Comment by isuruf** [comment]
Travis kills builds at 50 mins. Travis-CI also kills builds that have no output for 10 mins. `travis_wait` increases this timeout, not the overall timeout.

**Comment by leofang** [comment]
Ah that explains, thanks Isuru. So there's no way to bump the overall (50-min) timeout?

Regardless, I think this PR is a proper fix.

**Comment by leofang** [comment]
Friendly nudge @conda-forge/conda-smithy 🙂

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
