### PR TITLE
Enable reporting by default

### PR DESCRIPTION
**Pull request by mariusvniekerk**
Checklist
* [ ] Added a ``news`` entry

### CODE REVIEW

**Comment by isuruf** [comment]
Does this work? Feedstocks that had reporting disabled were reporting.

**Comment by mariusvniekerk** [comment]
It mostly does.  I'm not quite sure why things that were flagged as not reporting did when they weren't supposed to.  I've also bulk enabled all of the feedstocks manually. So we should see builds everywhere

**Comment by scopatz** [comment]
Lgtm

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
