### PR TITLE
Enable CI via pre-commit

### PR DESCRIPTION
**Pull request by jakirkham**
This borrows the same config used successfully elsewhere in conda-forge to configure pre-commit.ci on conda-smithy. Also allows us to ask a bot to fix style issues (like is done in those repos). Drops the GHA config since that is now duplicative.

* https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4819
* https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/569

Checklist
* [ ] Added a ``news`` entry

### CODE REVIEW

**Comment by jakirkham** [comment]
Will want to enable this repo in the pre-commit GH settings after this is merged. Am happy to make that change

Screenshot 2023-10-26 at 1 43 00 PM

**Comment by jakirkham** [comment]
This is not a user facing feature. So didn't add a new entry. Though if folks want one, am happy to add it

**Comment by isuruf** [comment]
Thanks

**Comment by jakirkham** [comment]
Thanks for the review! 🙏

Have configured on GH

Screenshot 2023-10-27 at 4 21 30 PM

Also did a brief test in PR ( https://github.com/conda-forge/conda-smithy/pull/1788 ), which appears to work as expected

**Pull request merged**
