### PR TITLE
Remove stars and spaces from config file names

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [x] Added a ``news`` entry

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge/core, ready for review

**Comment by isuruf** [comment]
Which actual problem are you referring to?
I'm referring to a problem where `*` is not a valid file name in windows.

**Comment by beckermr** [comment]
Exactly! I didn't know what this PR solved until you wrote your comment above, but the code clearly works. Merge merge merge!

**Comment by isuruf** [comment]
Thanks @beckermr

**Pull request merged**
