### PR TITLE
Use pip in noarch: python

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by CJ-Wright** [comment]
Would it be possible to revisit this decision? Why is the only syntax that works for `noarch: python`? Is that still true or was this a momentary issue?

I'd like to know if we should move at least 187 packages which have the `python setup.py install ...` syntax over to the pip syntax.

xref: https://github.com/regro/cf-scripts/issues/183

**Comment by ocefpaf** [comment]
I guess that the statement `noarch and python setup.py doesn't work` is not entirely true. It does work most of the time.

@isuruf when you added this what was the issue you were experiencing?

**Comment by isuruf** [comment]
I think it was https://github.com/conda-forge/conda-forge.github.io/issues/519. Sorry, should have mentioned the issue in the PR.

**Comment by ocefpaf** [comment]
Thanks @isuruf!

I guess that we should change this to a non-failing test and suggest the change instead. If you agree I can implement that.

**Pull request merged**
