### PR TITLE
Update license year

### PR DESCRIPTION
**Pull request by BastianZim**
Checklist
* [ ] Added a ``news`` entry

### CODE REVIEW

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
Actually can you please update this file as well?

https://github.com/conda-forge/conda-smithy/blob/1e3c16fdb53c6eaf9eeb2d69b6c019489f96b212/conda_smithy/feedstock_content/LICENSE.txt

**Comment by BastianZim** [comment]
Good to go!

**Comment by jakirkham** [comment]
Great, thank you! 😄

**Comment by BastianZim** [comment]
Happy to help! Thanks for merging everything. 😃

**Comment by jakirkham** [comment]
Thanks for all of these PRs. It's important to update this stuff, but is easy for us to forget

**Comment by BastianZim** [comment]
Don't mention it, very happy to help! 😃
By the way, this seems like something that could be easily automated, either with GitHub actions and a bit of regex or by using something like this: https://github.com/marketplace/actions/update-license-copyright-year-s (Although I personally don't like using third-party actions that I haven't verified). 
Has there ever been any discussion in this direction?

**Comment by jakirkham** [comment]
Yeah that seems like a good idea. Thanks for the suggestion. Is this something you might be interested in working on (maybe with some guidance)? 🙂

cc @beckermr (who may have thoughts here 😉)

**Comment by BastianZim** [comment]
Sure, I could definitely try to take a stab at this. 😃
Bit busy currently but I should have some more time soon. Pending @beckermr’s input, I’d also create a separate issue to keep track of everything.

**Pull request merged**
