### PR TITLE
Remove vs2008 support

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [x] Added a ``news`` entry

### CODE REVIEW

**Comment by jakirkham** [comment]
+1 on removing this

IIRC we previously had some bot action or something that would readd VS 2008/Python 2.7 to a feedstock. Should we remove that as well (assuming it hasn't already been removed)?

cc @beckermr

**Comment by beckermr** [comment]
I don't recall this. Feel free to remove if you know where it is.

**Comment by jakirkham** [comment]
Referring to this ( https://github.com/conda-forge/conda-forge.github.io/pull/1008 ). Though not sure where it lived

**Comment by isuruf** [comment]
Merging now. I'll remove the webservices command in a follow up PR

**Comment by jakirkham** [comment]
Raised follow up issues:

* https://github.com/conda-forge/conda-forge-webservices/issues/500
* https://github.com/conda-forge/conda-forge.github.io/issues/1773

**Pull request merged**
