### PR TITLE
Drop `disabled_appveyor.yml`

### PR DESCRIPTION
**Pull request by jakirkham**
This initially seemed like a good idea. Honestly though it feels a bit half-baked in retrospect and doesn't server a very useful purpose. So this reverts PR ( https://github.com/conda-forge/conda-smithy/pull/94 ) to clean out some unnecessary stuff.

### CODE REVIEW

**Comment by jakirkham** [comment]
Hmm...maybe we should be removing the `disabled_appveyor.yml` files if they exist too.

**Comment by pelson** [comment]
> Hmm...maybe we should be removing the disabled_appveyor.yml files if they exist too.

Maybe we should. No rush on that one though. Let's keep track of it as an issue, but we don't need to do that for v1.

**Comment by jakirkham** [comment]
It just changes one piece of clutter in `conda-smithy` for another though. I almost wonder if we could go through with this and write a one off script to blow away `disabled_appveyor.yml` files from all feedstocks that have them.

**Comment by pelson** [comment]
> It just changes one piece of clutter in conda-smithy for another though. I almost wonder if we could go through with this and write a one off script to blow away disabled_appveyor.yml files from all feedstocks that have them.

Nice suggestion. We certainly have the tools to achieve this in relatively short order.

**Comment by jakirkham** [comment]
One off script it is. 😄

**Comment by jakirkham** [comment]
Just as FYI, we can see which feedstocks have this file with this [search]( https://github.com/search?q=org%3Aconda-forge+in%3Apath+disabled_appveyor.yml&type=Code ). Appears to be ~40.

**Comment by jakirkham** [comment]
Went ahead and added PR ( https://github.com/conda-forge/conda-smithy/pull/247 ) to clean up stray `disabled_appveyor.yml` files.

**Pull request merged**
