### PR TITLE
lint pinnings and add conda smithy update-pinning

### PR DESCRIPTION
**Pull request by croth1**
This will work if we decide to merge  https://github.com/conda-forge/staged-recipes/pull/2267

the commit
  * fixes https://github.com/conda-forge/conda-forge.github.io/pull/310 and implements https://github.com/conda-forge/conda-forge.github.io/issues/270
  * gives the linter the capability to check if the pinning is correct
  * adds a new `update-pinning` command to conda smithy to automatically update all pins

### CODE REVIEW

**Comment by jakirkham** [comment]
Toggling to restart CI.

**Comment by jakirkham** [comment]
I like this solution, @croth1. This is very cool. I'll try to take some time to look at it more in the coming week or so.

Tried to make some changes to how we are doing testing on CI to hopefully make it more clear what is causing the failure here.

**Comment by jakirkham** [comment]
Also, in light of the movement of this code to `conda-smithy`, do we actually need code to read the pinnings external from this?

**Comment by croth1** [comment]
We had a similar discussion a couple of months ago in which we argued that the pinnings should be independent of smithy. IIRC correctly the argument was that this would speed up smithy's release cycle too much. I'll link the discussion when I find it.

We then decided to move the pinnings to an extra package. We can revert this. I actually don't have a strong opinion on that.

Having the pinnings as json might have a future application at the moment all tools that require pinnings already depend on smithy.

**Comment by jakirkham** [comment]
Sorry, I should clarify. What I mean is the code reading the pinnings could be moved to `conda-smithy`, but the pinnings themselves could stay a separate package. Or is there something else you are thinking about here?

**Comment by croth1** [comment]
Ah again either way is fine - we can move them to smithy or leave them in the pinning package.

We will reuse these functions in the web service that sends pull requests after pin updates - but IIRC it already depends on smithy, so we should be fine either way.

**Comment by jakirkham** [comment]
> We will reuse these functions in the web service that sends pull requests after pin updates - but IIRC it already depends on smithy...

Yep, I would like to use the nice functionality you have provide here anywhere it can help including the pinning service.

**Comment by croth1** [comment]
@jakirkham shall I move the helper functions to smithy or leave them in the pinning package?

**Comment by jakirkham** [comment]
I think they should move to `conda-smithy`.

**Comment by croth1** [comment]
@jakirkham should be done

**Comment by croth1** [comment]
xref: https://github.com/conda-forge/aubio-feedstock/pull/6

**Pull request closed without merging**
