### PR TITLE
Add news for merge_build_host: True #[win]

### PR DESCRIPTION
**Pull request by justcalamari**

### CODE REVIEW

**Comment by justcalamari** [comment]
CC @CJ-Wright

**Comment by scopatz** [comment]
Just news, merging.

**Comment by CJ-Wright** [comment]
:+1: I'm going to run another release so we can get this into production (and run all the r based recipe syntax migrations)

**Comment by isuruf** [comment]
@CJ-Wright, shall we merge https://github.com/conda-forge/conda-smithy/pull/854 for the new release?

**Pull request merged**
