### PR TITLE
Simplify collection of current maintainers

### PR DESCRIPTION
**Pull request by jakirkham**
Only iterate over the current maintainers of a feedstock listed on the GitHub team when the team exists. Otherwise we know there are no maintainers and this iteration is unneeded.

Also handle additions to the feedstock team and the all-members team in the same loop to avoid performing the same checks twice.

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks for taking a look, @scopatz.

The CI failure is not unique to this PR. It can be demonstrated on `master` using a recent cron job. Have filed it as issue ( https://github.com/conda-forge/conda-smithy/issues/911 ), which includes more details.

**Comment by jakirkham** [comment]
@isuruf, could you please review this when you have a chance?

**Comment by scopatz** [comment]
pinging this!

**Comment by jakirkham** [comment]
Friendly nudge 😉

**Pull request merged**
