### PR TITLE
Only add new lines directly after new content

### PR DESCRIPTION
**Pull request by jwillemsen**
* conda_smithy/templates/README.md.tmpl:

### CODE REVIEW

**Review by scopatz — APPROVED** [review]

**Comment by isuruf** [comment]
I don't see how this changes anything

**Comment by jakirkham** [comment]
Yeah I think this is just a matter of adding some `-` probably in the `endif`. There's a little bit of fiddling to get this sort of thing right. Fortunately the space of parameters to explore is quite small 🙂

**Comment by jwillemsen** [comment]
Tried a few things using a jinja2 live parser but couldn't get something that removed the empty line when a variable is not set.

**Review by isuruf — APPROVED** [review]
Thanks

**Comment by jakirkham** [comment]
Thanks Johnny! Know fiddling with Jinja whitespace is a little tedious. We appreciate the effort 🙂

**Comment by jwillemsen** [comment]
Yes, sorting this out took some time, it doesn't work as I thought it works. This is my last change for conda-smithy, just wanted to assist a user with packaging ACE through conda, now back to my real work ;-)

**Pull request merged**
