### PR TITLE
Optionally use CircleCI OSX builds

### PR DESCRIPTION
**Pull request by isuruf**
```yaml
provider:
  osx: circle
```
in `conda-forge.yml` changes the rerendering to skip travis and use circleci for osx.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@gillins I believe you may be interest in this to build some of the long running builds that are failing now due to Travis-CI time out.

**Comment by isuruf** [comment]
TODO:
- Fix the case where there is no linux build, but there is a osx build.

**Comment by jakirkham** [comment]
Would encourage a little more generality in the config to avoid lock in should other CI options arrive in the future for the various platforms. Maybe something like this...

```yaml
provider:
  osx: circle
```

Mentioning this as NVIDIA supported Linux CI for GPUs is on the near horizon. Also discussion about other build providers occurred recently at the conference. So keeping this extensible for those options would be ideal.

**Comment by isuruf** [comment]
Done.

**Comment by ocefpaf** [comment]
@isuruf I just re-rendered the `qtwebkit` with your latest commit and got:

```shell
D  .appveyor.yml
D  .ci_support/linux_.yaml
D  .ci_support/win_.yaml
D  .circleci/checkout_merge_commit.sh
M  .circleci/config.yml
D  .circleci/fast_finish_ci_pr_build.sh
D  .circleci/run_docker_build.sh
D  .circleci/run_osx_build.sh
A  .travis.yml
M  README.md
```

That does not seems right to me :-/

**Comment by isuruf** [comment]
Did you change the conda-forge.yml to the new way at the top of the PR?

**Comment by ocefpaf** [comment]
> Did you change the conda-forge.yml to the new way at the top of the PR?

Ack! No :-(

I kind of like the old one. Bundling tons of stuff under provider may be confusing. Either way this won't be read and edited a lot so I don't really care.

Thanks @isuruf for this PR. I believe that https://github.com/conda-forge/qtwebkit-feedstock/pull/3 is a proof that this is ready to be merged as soon as you say you are done tweaking it.

**Comment by ocefpaf** [comment]
@isuruf any more tweaks?

https://github.com/conda-forge/qtwebkit-feedstock/pull/3 is green and ready to go!

**Comment by isuruf** [comment]
Now that 3.0.0 is tagged, this is ready to go.

**Comment by ocefpaf** [comment]
I was hoping to get this in 3.0.0 :smile:

**Comment by jakirkham** [comment]
Thanks @isuruf for doing this and @ocefpaf for testing.

**Pull request merged**
