### PR TITLE
don't fail for bioconda recipes

### PR DESCRIPTION
**Pull request by ocefpaf**
@bgruening not sure if you wrote this but you are my point of contact for `bioconda` recipes :smile: 

Can you please review it?

### CODE REVIEW

**Comment by ocefpaf** [comment]
Thanks @isuruf!

**Comment by isuruf** [comment]
@ocefpaf, can you add news entries for this PR and pip PR?

**Comment by ocefpaf** [comment]
The format for that is unclear to me. Are you going to create one file per PR like you did here: https://github.com/conda-forge/conda-smithy/pull/812/files ?

**Comment by isuruf** [comment]
Yes. One file per PR policy is to avoid merge conflicts. (In this case you can add both to one news file) Use a unique name for the news entry file and they'll all be merged together.

**Pull request merged**
