### PR TITLE
Add options to disable CIs

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Added a ``news`` entry

you can use

````
$ conda-smithy register-ci --help                                                                                                                             
usage: a tool to help create, administer and manage feedstocks. register-ci
       [-h] [--feedstock_directory FEEDSTOCK_DIRECTORY]
       [--user USER | --organization ORGANIZATION] [--without-azure]
       [--without-travis] [--without-circle] [--without-appveyor]

optional arguments:
  -h, --help            show this help message and exit
  --feedstock_directory FEEDSTOCK_DIRECTORY
                        The directory of the feedstock git repository.
  --user USER           github username under which to register this repo
  --organization ORGANIZATION
                        github organisation under which to register this repo
  --without-azure       If set, Azure will be not registered
  --without-travis      If set, Travis will be not registered
  --without-circle      If set, Circle will be not registered
  --without-appveyor    If set, Appveyor will be not registered

```

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
@hmaarrfk can you add a news entry?

**Comment by hmaarrfk** [comment]
I think there was some talk about "disabling azure by default", do you want me to add back the `--with` options?

**Comment by mariusvniekerk** [comment]
Please don't disable azure by default. We have several thousand feedstocks already registered there.

**Comment by hmaarrfk** [comment]
(Gah sorry, my hacks for shippable got added in accidentally).

**Comment by scopatz** [comment]
@hmaarrfk - is this ready for another look?

**Comment by hmaarrfk** [comment]
@scopatz Yes.

**Pull request merged**
