### PR TITLE
Drone update and apply black to fix formatting

### PR DESCRIPTION
**Pull request by chrisburr**
Contains #1185 with black applied to fix formatting. Looks like they now add trailing commas in multiline tuples/function argument declarations.

Update: I've moved to using `$DRONE_WORKSPACE` instead of `$CI_WORKSPACE`. It's not documented but appears to be the official supported variable: https://discourse.drone.io/t/feature-request-drone-project-dir-env-variable/4804/2

Checklist
* [x] Added a ``news`` entry

### CODE REVIEW

**Comment by chrisburr** [comment]
@conda-forge/core I've updated #1185 to fix the black formatting and in the processed noticed a better variable to use than `pwd` (see description). Can this get merged quickly to prevent all the drone builds for the Python 3.8 migration from failing?

Tested in https://github.com/conda-forge/davix-feedstock/pull/20

Closes #1185

**Comment by CJ-Wright** [comment]
This needs a merge and release?

**Comment by chrisburr** [comment]
@CJ-Wright Yup

**Comment by CJ-Wright** [comment]
@conda-forge/core I'll cut a release

**Comment by chrisburr** [comment]
Thanks @CJ-Wright! 🍰

**Pull request merged**
