### PR TITLE
Make the extras field contain a set and not a list

### PR DESCRIPTION
**Pull request by hmaarrfk**
Because all the other FIELDS are sets.

### CODE REVIEW

**Comment by scopatz** [comment]
Lgtm, but I am not super familiar here

**Comment by hmaarrfk** [comment]
I encountered it when trying to add a field to the outputs section. I wasn’t able to simply follow the line above it. 

https://github.com/conda-forge/conda-smithy/pull/879/files

**Comment by scopatz** [comment]
@isuruf @jakirkham - can you review this please?

**Comment by jakirkham** [comment]
I'll defer to @CJ-Wright. Seems like he has been more involved with `ruamel.yaml` and the linter lately.

**Comment by CJ-Wright** [comment]
I think this is reasonable since the `extra` values are dicts and the keys of dicts constitutes a set.

**Pull request merged**
