### PR TITLE
fix tests?

### PR DESCRIPTION
**Pull request by CJ-Wright**
This fixes the tests to eliminate #844 but I don't know if the new values are ok or not.

### CODE REVIEW

**Comment by isuruf** [comment]
`jpeg` should not be a top-level key. Correct value is 13

**Comment by CJ-Wright** [comment]
Hmm ok I can dump out more output if that is of interest. 

@msarahan thoughts?

**Comment by msarahan** [comment]
please see @isuruf comments on https://github.com/conda/conda-build/pull/2973#pullrequestreview-139592663

I believe that is the proper fix.

**Comment by CJ-Wright** [comment]
Cool, I'm closing this.

**Pull request closed without merging**
