### PR TITLE
Pass MAKEFLAGS for circleci builds

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by jakirkham** [comment]
Basically, what this does is let us use `MAKEFLAGS`. This is automatically passed through by `conda-build`. In staged-recipes, we are using this to allow parallel builds of a fixed amount of parallelism according to the CIs that allow it. Currently this is CircleCI with parallelism of 2. This would make the same change for the feedstocks.

**Comment by jakirkham** [comment]
Thanks for adding this, @jschueller. I tried to add a rough explanation above feel free to take any parts of it and add it to the summary here so it is clear to others what we are trying to accomplish.

**Comment by jschueller** [comment]
@jakirkham perfect

**Comment by jschueller** [comment]
@jakirkham, ok, I edited the commit message.

**Comment by jschueller** [comment]
@jakirkham, hi, did you forget to merge this ?

**Comment by pelson** [comment]
I'm :+1: on the change, but :-1: on doing it here.
You have hit me at an unfortunate time @jschueller - I'd like to start reducing specialisms like this in the feedstocks themselves, and let them be part of the toolchain package https://github.com/conda-forge/toolchain-feedstock. Does that work @jakirkham?

Thanks for submitting this @jschueller - I think it is the right thing to do for conda-forge. :+1:

**Comment by jschueller** [comment]
@pelson, @jakirkham see https://github.com/conda-forge/toolchain-feedstock/pull/6

**Comment by pelson** [comment]
> @pelson, @jakirkham see conda-forge/toolchain-feedstock#6

Amazing. Thanks @jschueller :+1:

**Comment by jakirkham** [comment]
> I'm :+1: on the change, but :-1: on doing it here.

That's fine.

> You have hit me at an unfortunate time @jschueller - I'd like to start reducing specialisms like this in the feedstocks themselves, and let them be part of the toolchain package https://github.com/conda-forge/toolchain-feedstock. Does that work @jakirkham?

👎

It should live somewhere either here, ( https://github.com/conda-forge/conda-forge-build-setup-feedstock ), or some other yet to be decided configuration package. However, I don't want this in the `toolchain`.

**Comment by kynan** [comment]
Was there any progress on this since? What's the recommended method of using multiple build threads with `make`? @pelson @jakirkham

**Comment by kynan** [comment]
Did some more research on this:
* The [CircleCI ubuntu image](https://circleci.com/docs/build-image-trusty/) ships coreutils i.e. we can use `nproc` to get the number of logical cores
* On OSX [we can get the number of logical cores](https://stackoverflow.com/a/1715612) with `sysctl -n hw.ncpu`

**Comment by jschueller** [comment]
The correct way is to use CPU_COUNT.

**Comment by jakirkham** [comment]
@jschueller is correct. We ultimately override `CPU_COUNT` in `conda-forge-build-setup` to the number of CPUs the CIs tell us that they give us in their docs, which `conda-build` takes as a pass through environment variable. So using `CPU_COUNT` is the way to go.

**Comment by kynan** [comment]
@jschueller @jakirkham can / should we be using `CPU_COUNT` in our build scripts? Or are you thinking of adding `-j ${CPU_COUNT}` to the default `make` flags?

**Comment by jakirkham** [comment]
We tried using `MAKEFLAGS` and decided as a community that we didn't like it. We decided that using `CPU_COUNT` directly in your build scripts was the way to go.

xref: https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/18
xref: https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/24

**Comment by kynan** [comment]
@jakirkham Absolutely agree with that decision, just wanted to know what's the way to go!

**Comment by jakirkham** [comment]
Oh sorry, was merely trying to provide background on what happened since this PR.

**Comment by kynan** [comment]
Sure, thanks for doing that!

**Pull request closed without merging**
