### PR TITLE
entry_points

### LINKED ISSUE #6: Convert scripts to entry points in setup.py

### PR DESCRIPTION
**Pull request by ocefpaf**
Closes #6 (Needs  #2 to work properly though!)

### CODE REVIEW

**Comment by scopatz** [comment]
This needs an update now @ocefpaf

**Comment by mwcraig** [comment]
I'll try it again after the rebase, but right now the script gets installed (good) but I get an import error that is different than #2:

```python
$ conda smithy
Traceback (most recent call last):
  File "/Users/mcraig/miniconda/bin/conda-smithy", line 9, in <module>
    load_entry_point('conda-smithy==0.1.0.dev0', 'console_scripts', 'conda-smithy')()
  File "build/bdist.macosx-10.5-x86_64/egg/pkg_resources/__init__.py", line 558, in load_entry_point
  File "build/bdist.macosx-10.5-x86_64/egg/pkg_resources/__init__.py", line 2682, in load_entry_point
  File "build/bdist.macosx-10.5-x86_64/egg/pkg_resources/__init__.py", line 2355, in load
  File "build/bdist.macosx-10.5-x86_64/egg/pkg_resources/__init__.py", line 2361, in resolve
  File "/Users/mcraig/miniconda/lib/python2.7/site-packages/conda_smithy-0.1.0.dev0-py2.7.egg/conda_smithy/conda_smithy.py", line 10, in <module>
    import conda_smithy.configure_circle_ci as configure_circle_ci
ImportError: No module named configure_circle_ci
```

**Comment by ocefpaf** [comment]
@scopatz rebased.

@mwcraig before and after the rebase I got:

```python
> conda smithy
Traceback (most recent call last):
  File "/home/filipe/miniconda/bin/conda-smithy", line 10, in <module>
    import conda_smithy.configure_circle_ci as configure_circle_ci
  File "/home/filipe/miniconda/lib/python2.7/site-packages/conda_smithy/configure_circle_ci.py", line 13, in <module>
    with open(os.path.expanduser('~/.conda-smithy/circle.token'), 'r') as fh:
IOError: [Errno 2] No such file or directory: '/home/filipe/.conda-smithy/circle.token'
```

Not sure what is going on there...

I added an [extra commit](https://github.com/ocefpaf/conda-smithy/commit/7b936c2cae5e0b2775a96615e966a2cf71cc15a3) that I forgot.  Hopefully that was it.

**Comment by mwcraig** [comment]
I'm still seeing the same error I was before, will get a chance to investigate later today.

**Comment by mwcraig** [comment]
@ocefpaf -- I did a quick patch for #2. I think if you rebase now and then try this you will hit the same issue I was. I'm about to open a PR on your PR that has the last couple of fixes, I think.

**Comment by ocefpaf** [comment]
I merged your patch, rebased, and here is what I get:

```python
No circle token. Put one in ~/.conda-smithy/circle.token
No appveyor token. Put one in ~/.conda-smithy/appveyor.token
Traceback (most recent call last):
  File "/home/filipe/miniconda/bin/conda-smithy", line 9, in <module>
    load_entry_point('conda-smithy==0.1.0.dev0', 'console_scripts', 'conda-smithy')()
  File "/home/filipe/miniconda/lib/python2.7/site-packages/conda_smithy/conda_smithy.py", line 164, in main
    args.subcommand_func(args)
  File "/home/filipe/miniconda/lib/python2.7/site-packages/conda_smithy/conda_smithy.py", line 64, in __call__
    meta = MetaData(args.recipe_directory)
  File "/home/filipe/miniconda/lib/python2.7/site-packages/conda_build/metadata.py", line 257, in __init__
    assert isdir(path)
AssertionError
```

**Comment by mwcraig** [comment]
@ocefpaf -- that is the expected output at the moment with no arguments :) 

@pelson -- can we merge this before you rebase #7?

**Comment by pelson** [comment]
Sure can. Looks good - I've never used entry_points either so good to learn :+1:

**Comment by mwcraig** [comment]
ok, I'm online for the rest of the day, give me a shout if needed.

**Comment by pelson** [comment]
> ok, I'm online for the rest of the day, give me a shout if needed.

Should get a good few hours this evening, so will let you know how I get on. Could do with adding some tests + exploring the registration of the github repos on travis/appveyor/circle again.

**Pull request merged**
