### PR TITLE
Fix AppVeyor project URL

### PR DESCRIPTION
**Pull request by ocefpaf**
Closes https://github.com/conda-forge/staged-recipes/issues/267

### CODE REVIEW

**Comment by jakirkham** [comment]
Is this planned to be released?

**Comment by pelson** [comment]
> Is this planned to be released?

I was just looking at that. We need to remove homebrew from staged-recipes before we can reliably release conda-smithy I think.

**Comment by ocefpaf** [comment]
> I was just looking at that. We need to remove homebrew from staged-recipes before we can reliably release conda-smithy I think.

PR inbound.

**Comment by jakirkham** [comment]
Are you going to temporarily revert the homebrew fix? Admittedly, we are going to have to address this at some point. Maybe now is the time?

**Comment by ocefpaf** [comment]
Done in https://github.com/conda-forge/staged-recipes/pull/270

**Comment by pelson** [comment]
> Are you going to temporarily revert the homebrew fix? Admittedly, we are going to have to address this at some point. Maybe now is the time?

Nope. We start rolling it out - it is the right thing to do. When we find an issue, we will have to address it :smile:

**Comment by jakirkham** [comment]
Sounds good. I might not be able to start fixing things for a bit, but will get on it as soon as I can.

**Comment by pelson** [comment]
Just tagged the release. https://github.com/conda-forge/conda-smithy/releases/tag/v0.8.3

**Comment by pelson** [comment]
https://github.com/conda-forge/conda-smithy-feedstock/pull/16

**Comment by jakirkham** [comment]
We need to do this to the badge too.

**Pull request merged**
