### PR TITLE
Remove items() from jinja2 dict so that it can be sorted

### PR DESCRIPTION
**Pull request by ericdill**
Also sort the dict because deterministic jinja output is good

### CODE REVIEW

**Comment by ericdill** [comment]
If I try to sort this dictionary with the `dictsort` jinja function then it raises with the following traceback:

```
Traceback (most recent call last):
  File "/Users/edill/mc/bin/conda-smithy", line 9, in <module>
    load_entry_point('conda-smithy==0.1.0.dev0', 'console_scripts', 'conda-smithy')()
  File "/Users/edill/dev/conda/conda-forge/conda-smithy/conda_smithy/conda_smithy.py", line 165, in main
    args.subcommand_func(args)
  File "/Users/edill/dev/conda/conda-forge/conda-smithy/conda_smithy/conda_smithy.py", line 67, in __call__
    generate_feedstock_content(feedstock_directory, args.recipe_directory)
  File "/Users/edill/dev/conda/conda-forge/conda-smithy/conda_smithy/conda_smithy.py", line 27, in generate_feedstock_content
    configure_feedstock.main(target_directory)
  File "/Users/edill/dev/conda/conda-forge/conda-smithy/conda_smithy/configure_feedstock.py", line 185, in main
    render_travis(env, config, forge_dir)
  File "/Users/edill/dev/conda/conda-forge/conda-smithy/conda_smithy/configure_feedstock.py", line 39, in render_travis
    fh.write(template.render(**forge_config))
  File "/Users/edill/mc/lib/python3.4/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/edill/mc/lib/python3.4/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/edill/mc/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/edill/dev/conda/conda-forge/conda-smithy/conda_smithy/templates/travis.yml.tmpl", line 10, in top-level template code
    {% block env %}
  File "/Users/edill/dev/conda/conda-forge/conda-smithy/conda_smithy/templates/travis.yml.tmpl", line 23, in block "env"
    {% for name, hashed_secure in travis.secure.items() | dictsort %}
  File "/Users/edill/mc/lib/python3.4/site-packages/jinja2/filters.py", line 223, in do_dictsort
    return sorted(value.items(), key=sort_func)
AttributeError: 'dict_items' object has no attribute 'items'
```

**Comment by scopatz** [comment]
Wait, so should this be merged?

**Comment by ericdill** [comment]
My comments on this PR have been pretty unclear, apologies.  My first attempt at sorting this dictionary was just to add `| dictsort`.  That raised the above stack trace, which led to some confusion. Apparently you need to remove the `.items()` for dictsort to work.

Yes, this should be merged.

**Comment by scopatz** [comment]
I see.  Thanks for the clarification.

**Comment by scopatz** [comment]
Thanks again!

**Pull request merged**
