### PR TITLE
Remove `update-cb3` command

### PR DESCRIPTION
**Pull request by xhochy**
The compiler migration is now more than three years ago (probably already four) and things have changed since then. Let's get rid of this command instead of maintained/updating it.

Checklist
* [x] Added a ``news`` entry

### CODE REVIEW

**Review by beckermr — COMMENTED** [review]
Any dead code in the test suite?

**Comment by beckermr** [comment]
nvm tests passed

**Review by beckermr — APPROVED** [review]

**Comment by xhochy** [comment]
It looks like this didn't have any tests.

**Comment by beckermr** [comment]
One other item is that this needs to be removed from the webservices code as well. That is another PR in another spot though.

**Comment by xhochy** [comment]
> One other item is that this needs to be removed from the webservices code as well. That is another PR in another spot though.

On it, just waiting for the CI to pass before I request your review there: https://github.com/conda-forge/conda-forge-webservices/pull/564

**Comment by jakirkham** [comment]
Thank you both! 🙏

Nice to see the cb3 bits leaving our codebase 👋

**Comment by isuruf** [comment]
cb2. :smile:

**Pull request merged**
