### PR TITLE
Add hook for updating teams

### PR DESCRIPTION
**Pull request by isuruf**
Needed for https://github.com/conda-forge/conda-forge-webservices/pull/96

### CODE REVIEW

**Comment by isuruf** [comment]
@ocefpaf, ping

**Comment by ocefpaf** [comment]
pong

**Comment by ocefpaf** [comment]
Let me know when we are good for a new release with these new features!

**Comment by isuruf** [comment]
@ocefpaf, I think it'll be good to have a new release now, especially with #531

**Comment by ocefpaf** [comment]
OK. I'll do it early tomorrow if no one beats me to it. (It happy hour time here :smile:)

**Comment by isuruf** [comment]
Done. https://github.com/conda-forge/conda-smithy/releases/tag/v2.4.0

**Pull request merged**
