### PR TITLE
Add linter check for willing maintainers

### LINKED ISSUE #1791: [Feature request] Add linter for staged-recipes, checking if maintainers have agreed
This is a continuation of https://matrix.to/#/!SOyumkgPRWoXfQYIFH:matrix.org/$169940345027597QzKsX:matrix.org?via=matrix.org&via=gitter.im&via=cadair.com

In short: in staged-recipes, we make sure before merging that all maintainers listed in the feedstock have agreed to be listed there. This is a tickbox in the PR description so, in theory submitters should check themselves but that is not always the case.

This issue is to discuss, if it makes sense to have a linter check, which checks if all of the maintainers listed have interacted with the PR and then displays a message, if that is not the case.

The difficulty is, that conda-smithy currently lints the recipe without knowing the PR the recipe is in which makes it impossible to see who has interacted with the PR. 
Hence, the two steps for implementing this are

- [ ] Pass PR number from webservices to conda-smithy
- [ ] Add the function to conda-smithy. Draft is here: https://github.com/conda-forge/conda-smithy/pull/1792

The relevant function in conda-smithy starts here: https://github.com/conda-forge/conda-smithy/blob/992fb6deca7294afa581fb7de5a1a9b30e3322bc/conda_smithy/lint_recipe.py#L808
The webservices linter is called here: https://github.com/conda-forge/conda-forge-webservices/blob/main/conda_forge_webservices/linting.py

### PR DESCRIPTION
**Pull request by BastianZim**
Checklist
* [x] Added a ``news`` entry

Closes #1791

### CODE REVIEW

**Comment by BastianZim** [comment]
pre-commit.ci autofix

**Comment by BastianZim** [comment]
pre-commit.ci autofix

**Comment by BastianZim** [comment]
pre-commit.ci autofix

**Comment by BastianZim** [comment]
Ok not sure if the error is due to rate limiting or the token, but I'm going to wait until we have figured out the PR number part.

**Comment by BastianZim** [comment]
pre-commit.ci autofix

**Comment by BastianZim** [comment]
Thanks Isuru!

**Comment by BastianZim** [comment]
Thank you, @isuruf! Are you happy with me trying to get something going in the webservices repo, or do you have something in mind already?

**Comment by isuruf** [comment]
Yes, a PR to webservices repo is welcome.

**Comment by BastianZim** [comment]
Thanks for the merge!

**Pull request merged**
