### PR TITLE
Mark macos specific variables as always used

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by jakirkham** [comment]
SGTM

**Comment by isuruf** [comment]
@msarahan, @jakirkham, I'm wondering whether these should be committed into CI matrix now. If we decide to only support say >=10.10 in the future, there's no need for a rebuild right?

**Comment by jakirkham** [comment]
I suppose. Though there is some value in being explicit about what SDK we used in the build. Also I can imagine that can be useful information when going back through git history.

**Comment by msarahan** [comment]
If you put it into the matrix now and it isn't doing anything, does it do any harm?  If it's already consistent with the current process, does it do any harm?  Unless it is doing harm (i.e. inconsistent with what is actually in use, because you're not yet using the new compilers, so you're subject to whatever the normal setup is, and that normal setup doesn't match), then this is fine.

**Comment by isuruf** [comment]
> If you put it into the matrix now and it isn't doing anything, does it do any harm? If it's already consistent with the current process, does it do any harm? Unless it is doing harm (i.e. inconsistent with what is actually in use, because you're not yet using the new compilers, so you're subject to whatever the normal setup is, and that normal setup doesn't match), then this is fine.

This might become a problem when we have to update to 10.10 with my plan to resurrect `conda-forge-maintenance` bot, but I guess we can handle that with a hack then

**Pull request merged**
