### PR TITLE
WIP unique tokens per CI and append tokens to registry

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [ ] Added a ``news`` entry

### CODE REVIEW

**Comment by jakirkham** [comment]
Is there a reason this was closed?

**Comment by beckermr** [comment]
See the other open prs

**Comment by jakirkham** [comment]
This one ( https://github.com/conda-forge/conda-smithy/issues/1716 )?

**Comment by beckermr** [comment]
Yes, I split this big one into two smaller requests and changed the token format to make rotations easier. See this issue for tracking work: https://github.com/conda-forge/conda-forge.github.io/issues/1888

**Pull request closed without merging**
