### PR TITLE
make sure to keep the fortran compiler version

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [ ] Added a ``news`` entry

### CODE REVIEW

**Comment by scopatz** [comment]
LGTM but please add a news entry: https://regro.github.io/rever-docs/news.html

**Comment by isuruf** [comment]
This should be done by conda-build automatically. Are you sure the feedstock was rerendered? If not, can you open an issue in conda-build?

**Comment by richardjgowers** [comment]
@isuruf yeah I rerendered the feedstock manually here: https://github.com/conda-forge/yaehmop-feedstock/pull/3/commits/706d27fe53d87b53ba418fbeb47408241761398f

**Comment by beckermr** [comment]
I believe it was rerendered manually @isuruf, but I did not do it myself. 

I am confused though. Where does conda-build see the global pinnings file in the CI scripts? All I see for calling the build is here

```
{% if idle_timeout_minutes %}travis_wait {{ idle_timeout_minutes }}{% endif %} conda build ./{{ recipe_dir }} -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./{{ recipe_dir }} ./.ci_support/${CONFIG}.yaml
```

https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/templates/travis.yml.tmpl#L75

This does not use -m with the global pinnings file.

Are you saying this should be an internal default in conda-build?

**Comment by beckermr** [comment]
Will do on the news entry once we are ready to merge or not @scopatz !

**Comment by beckermr** [comment]
Well @isuruf I cannot find where conda-build is supposed to set a version on the osx fortran compiler. If you have tips on what to put in the issue upstream I am happy to help!

**Comment by isuruf** [comment]
conda-smithy will use the global pinnings file and render the recipe using conda-build. After that conda-smithy asks which variables were used from conda-build and stores them in YAML files in .ci_support directories. If the fortran_compiler_version variable is not saved it's not used. For example see the YAML files in numpy-feedstock

**Comment by beckermr** [comment]
Right OK. So this PR forces the fortran compiler version to be properly saved in the CI directories. Thus I don't think this is a conda-build issue. The version variable was not saved in the osx yaml, but now with this PR it is.

**Comment by isuruf** [comment]
It is an issue with conda-build or conda-smithy. This should happen automatically. For example, see the numpy-feedstock and the variable was stored automatically without this PR. We should figure out what happened instead of working around this problem.

**Comment by beckermr** [comment]
Ahhhh got it.

**Comment by beckermr** [comment]
OK This was an old version of conda-build. Closing.

**Pull request closed without merging**
