### PR TITLE
Toolchain3 for update-cb3

### PR DESCRIPTION
**Pull request by scopatz**
see https://github.com/regro/cf-scripts/issues/363

### CODE REVIEW

**Comment by scopatz** [comment]
@conda-forge/core This is ready for review!

**Comment by jakirkham** [comment]
Looks good. Were you able to try it locally?

**Comment by scopatz** [comment]
@jakirkham - nope I didn't try it locally, but I can.

**Comment by scopatz** [comment]
Seems to work locally:

```console
scopatz@artemis ~/feedstocks/hunspell master $ git checkout -b compiler_migration2 bot/compiler_migration2
Branch 'compiler_migration2' set up to track remote branch 'compiler_migration2' from 'bot'.
Switched to a new branch 'compiler_migration2'
scopatz@artemis ~/feedstocks/hunspell compiler_migration2 $ conda smithy update-cb3
List of changes done to the recipe:
Renamed build with host
Moving autoconf from host to build
Moving automake from host to build
Moving libtool from host to build
Moving make from host to build
Removing toolchain3 in favour of compiler()
Adding C compiler
Adding C++ compiler
scopatz@artemis ~/feedstocks/hunspell compiler_migration2 $ git diff
diff --git a/recipe/meta.yaml b/recipe/meta.yaml
index d15ddf4..7c35449 100644
--- a/recipe/meta.yaml
+++ b/recipe/meta.yaml
@@ -26,7 +26,9 @@ requirements:
     - {{ compiler('c') }}
     - {{ compiler('cxx') }}
   host:
-    - toolchain3
+    - {{ compiler('c') }}
+    - {{ compiler('cxx') }}
+  host:
     - gettext
     - readline
   run:
```

**Comment by jakirkham** [comment]
Hmm...did it add a second `host` section? Also looks like `compiler` was added to `host` as well. 😕

Admittedly as this appears to be a partially migrated recipe, this is a bit more complicated than one that hadn't been migrated at all. Not sure we should worry too much about how this behaves on partially migrated recipes, but I'll leave it up to you.

The code itself seems like it should work on an unmigrated recipe. IDK if there are any of those to still test. Maybe an earlier commit of this one would suffice?

**Comment by scopatz** [comment]
I think in situations like this where there has already been a partial migration (or syntax migration), we'll have to manually edit the files somewhat.  Some of these tools might actually need toolchain3 for the old compilers.  There should not be that many of them.

@mariusvniekerk - what is the selector that is used for the gcc7 label switching?

**Comment by jakirkham** [comment]
Thus far simply removing `toolchain3` from partially migrated recipes has worked nicely in my experience.

**Comment by scopatz** [comment]
Yeah, removing toolchain3 seems to work so far.

**Comment by jakirkham** [comment]
Well I'm ok with merging this if you are. WDYT?

**Comment by scopatz** [comment]
I think it is OK to merge this, because it at least bring toolchain3 in-line with toolchain, even if the solution is to ultimately remove toolchain3 from the recipe.

**Comment by mariusvniekerk** [comment]
@scopatz adding `compiler_stack: comp7` to conda-forge-congif.yaml makes the magic go

**Comment by jakirkham** [comment]
Thanks @scopatz 😄

**Comment by scopatz** [comment]
Thanks @jakirkham @mariusvniekerk!

**Pull request merged**
