### PR TITLE
Handle recipes with .zip urls

### PR DESCRIPTION
**Pull request by justcalamari**

### CODE REVIEW

**Comment by justcalamari** [comment]
CC @isuruf

**Comment by isuruf** [comment]
LGTM. Have you tried this PR with both type of urls?

**Comment by justcalamari** [comment]
Yes

**Comment by CJ-Wright** [comment]
Was this the main stumbling block for the 138 PRs which were not issued?

**Comment by justcalamari** [comment]
There are recipes failing for other reasons, but I think a lot were due to this.

**Comment by CJ-Wright** [comment]
@conda-forge/core can we cut a release with this? (All the terraform feedstocks are waiting on this)

**Comment by scopatz** [comment]
@CJ-Wright - you should have the rights to do a release and conda-smithy has a rever.xsh file :wink:

**Comment by CJ-Wright** [comment]
Yes I know, I usually want a little consensus and to double check with others.

**Comment by CJ-Wright** [comment]
I will cut a release on Monday unless anyone has objections.

**Comment by isuruf** [comment]
@CJ-Wright, can you add news items to the PRs without them?

**Comment by CJ-Wright** [comment]
Sure

**Pull request merged**
