### PR TITLE
Re-render directions

### PR DESCRIPTION
**Pull request by jakirkham**
Adds the long awaited simple directions for re-rendering a feedstock. This should hopefully make it easier to explain to people what is required if they need to do it themselves.

cc @conda-forge/core

### CODE REVIEW

**Comment by jakirkham** [comment]
Thoughts?

**Comment by mwcraig** [comment]
LGTM, though I haven't had a chance to try it out...

**Comment by jakirkham** [comment]
Is it alright if we merge then? It would be nice to refer people to a Readme section as opposed to copy-pasta or trying to link the Readme as changed by this PR.

**Comment by mwcraig** [comment]
Sure, done.

**Comment by jakirkham** [comment]
Thanks.

**Pull request merged**
