### PR TITLE
Check for SPDX expression and add a hint

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [x] Added a ``news`` entry

### CODE REVIEW

**Comment by CJ-Wright** [comment]
How does this handle things like `BSD 3-Clause` (I ran into this error a few days ago)?

Should we create a mini-migrator to fix bad license names (where we can intuit the correct license)?

**Comment by isuruf** [comment]
It will be rejected. (This is a hint only and not a full lint)

**Comment by isuruf** [comment]
@CJ-Wright, is it possible to get all the different license keys  in feedstocks and counts?

**Comment by CJ-Wright** [comment]
Sure, give me a few mins.

**Comment by CJ-Wright** [comment]
0,1
GPL3,19
MIT,2501
Apache-2.0,524
BSD-3-Clause,871
COPYING,1
LGPL-3.0,88
Public Domain,40
Apache 2,4
ISC,37
Apache 2.0,264
GPL v2+,5
BSD 3-Clause,461
BSD,115
GPL-3.0,252
LGPL v2.1,5
HPND,2
BSD 3-clause,119
BSD 2-Clause,91
OSI,2
GPLv3,47
LGPL 3,14
PSF 2,11
LGPL-2,11
LGPL-2.1+,3
LGPL,32
LGPL 2.1,10
BSD 2-clause,26
"BSD 3-Clause, PSF 2",1
BSD-3,20
EPL-1.0,3
LGPL-2.0,12
GPL-2.0,132
GPL 3,10
PSFL 2,1
Python Software Foundation,6
PSF2 & MIT,1
Python-2.0,6
CECILL-B,1
GPL-3.0-or-later,46
Custom,5
BSD-2-Clause,168
Apache,11
LGPLv3+,6
LGPLv3 or BSD,1
MPL-2.0,35
Biopython License Agreement,1
PSF,10
BSD-3-clause,23
Modified BSD License (3-clause),19
GNU General Public License v3 (GPLv3),8
Boost-1.0,6
GPLv2+,36
LGPL 2.1 or MPL 1.1,1
LGPL 2.1 and MPL 1.1,1
GPLv2,34
MPL 1.1,3
CCLRC,1
3-Clause BSD,5
fitsio,1
GPL2,17
GPL3/LGPL3,2
LGPL2,1
MIT/GPL3,2
LGPL-2.1,79
UI/NCSAOSL,1
Eclipse v1.0,2
CPL 1.0,1
CC-BY-4.0,3
LGPL v3+,2
MPL 2.0,86
BSD-3-Clause (or Apache 2.0),1
LGPL3,17
LGPL v2,2
MIT/X derivate (http://curl.haxx.se/docs/copyright.html),1
BSD-3-Clause-Attribution,1
LGPLv2+,3
PSF 2.0,4
GNU Lesser General Public v3 or later (LGPLv3+),3
BNL,2
MIT-Zero,1
AGPL-3.0,14
BSL-1.0,9
"Boost Software, Version 1.0",1
Public Domain Dedictation and BSD 2-Clause and PSF 2.1.1 and GPL 3.0,1
LGPL 3.0,6
UNLICENSE,2
AGPL 3.0,1
GPL v3 and LGPL v3,10
MPL2,2
CC0,12
GNU,1
LGPLv3,7
University of Illinois/NCSA (NCSA),1
NCSA,19
OTHER,18
"GPL v3.0, GPL v2.0, MIT, GPL, LGPL v3.0, BSD 3-Clause, Apache 2.0",1
LGPL-2+,1
LGPLv2.1+,3
ffx,1
Apache-2,5
Apache 2.0 or BSD 3-Clause,1
LGPL v2+,2
GPLv2 GPLv3 FreeImage,1
GPL-2,391
GPL-2.0 and FreeType,1
PUBLIC-DOMAIN,9
Affero GPL,1
Tumbolia Public,1
GPL v3+,2
GPL v2 and LGPL 2.1,1
GPL 2 and LGPL 3,1
Gnuplot,1
LGPLv2.1,2
BSD-Style,2
Apache 2.0 and MIT,1
GPL-3,363
LGPLv2,9
"BSD 2-Clause and triangle.[c,h] license, which is non-free for commercial use",1
GPL 2.0,11
HDF5,1
BSD-2,3
GPL v3,6
MPL 1.1/GPL 2.0/LGPL 2.1,1
GPL v1,1
BSD Like,1
ImageMagick,1
PSF2,1
"GPL 2, LGPL 2",1
LGPL-3.0 (for non-commercial/academic use),1
EPL 1.0,1
Open Government,1
LGLP-2.0,1
JasPer 2.0,1
IJG,1
Modified BSD,3
Python Software Foundation or MIT,1
Apache v2.0,4
MIT X-11,1
CCO,1
LGPL2.1,5
GPL_v3,1
UCAR/UNIDATA,1
GNU LGPL,1
NetBSD,1
GPLv3+,8
GD,1
SGI-2,1
GPL and LGPL,2
"IJG, modified 3-clause BSD and zlib",1
APSL-2.0,2
zlib/libpng,1
LGPL v3,1
PSF 1.0,1
BSD-2-clause,3
OpenLDAP Public,1
"BSD 3-Clause, GPL-2.0, ZPL-2.0, and ElementTree",1
PSF-based,2
Apachev2,1
"various, see http://miktex.org/copying",1
BSD v3,1
Apache2,2
MPICH,1
LGPL-3,23
3-clause,1
CeCILL-C,2
Free software (MIT-like),1
http://www.unidata.ucar.edu/software/netcdf/copyright.html,3
OSI Approved and MIT,1
GPL 2 and LGPL3,1
New Relic,1
Various,2
BSD 2-Clause (bundled triangle code is non-free for commercial use),1
"CPL-1.0, zlib, bzip2, LGPL, BSD, UNKNOWN",1
"MIT, ISC, BSD 2-Clause",1
GNU Affero GPL v3,2
"MIT, Public Domain",1
OpenSSL,1
AGPLv3,2
CC-BY-NC-3.0,2
GPL,77
Apache 2.0 or BSD 2-Clause,1
Non-free for commercial use,1
"BSD-2-Clause, PSF2",1
pbzip2,1
PCRE2,1
Public domain,3
Perl Artistic,1
perl,1
Perl 5,1
non-commercial use only,1
zlib,9
PIL,1
"BSD or Apache, Version 2.0",1
GPL 2,12
3-clause BSD,3
"GPLv3, MIT",1
Adobe+GPLv2,1
PortAudio,1
PostgreSQL,3
BSD3,4
"LGPL, BSD-like, ZPL",1
LGPL 2,1
Artistic-2.0,24
WTFPL,1
"LGPL 2.1, MPL 1.1",1
PSF-2-like,1
Public Domain/BSD 2-Clause/OCB/MPIR,1
Epics Open,2
BSD or GPL 2,1
MIT/BSD-3-Clause,1
GPLv2 with linking exception,1
CeCILL v2,1
AFL-3.0,1
CC0-4.0,1
GPL-3.0-only,5
PyNGL Source Code,1
BSD-like,5
GPL 2.0+/LGPL 2.1+/MPL 1.1,1
"Commercial, GPL-2.0, GPL-3.0",1
MIT X11 style,1
Public Domain/ZLIB,2
GPL 3.0,4
spherepack,1
BSD 3 Clause,2
CC0-1.0,15
OpenLDAP,1
LGPL 2.1+,1
BSD Clause,1
LBNL-BSD,1
BSD-3-Clauses,1
"Qwt, Version 1.0",2
GPL (>= 2),434
GPL-2 | GPL-3,52
ACM (Restricts use),1
CC BY-SA 4.0,5
GPL (>= 3),102
LGPL (>= 2.1),15
GPL-2.0 or GPL-3.0,1
BSD_2_clause,20
LGPL-3 | Apache 2.0,3
Unlimited,11
BSD_3_clause,32
GPL (>= 3) | file LICENCE,1
LGPL (>= 2),4
Artistic 2.0,1
FreeBSD | GPL-2 | file,1
GPL-2 and GPL-3,7
AGPL-3,11
GPL (>= 2.0),12
AGPL,2
LGPL (>= 2.0),2
GPL-2 | LGPL-2.1 | MPL-1.1,1
Lucent Public,1
GPL-2 (>= 2),1
BSL,1
Apache-2-0,5
CPL-1.0,1
BSD 2 Clause,1
GPL (>= 2,1
MPL (>= 2),1
GPL-2.0 | MIT,1
LGPL-2 | BSD_3_clause,1
FOSS,1
Unlicense,3
ISCL,1
CSIRO Open Source Software Agreement (GPLv3+),1
BSD 3-Clauses,1
BSD-3 Clause,1
Zope Public,1
W3C,2
Public-Domain (http://www.sqlite.org/copyright.html),1
BSD3-like,1
MIT/Apache 2.0,1
"LGPL v2 (AMD, BTF, etc), BSD 3-clause (UFget), GPL v2 (UMFPACK, RBIO, SPQR, GPUQRENGINE), Apache 2.0 (Metis)",1
ZPL-custom,1
BSD-derived,4
BSD-variant,1
GPL-2.0 and GPL-3.0,3
GPL-2.0+ and GPL-2.0 and GPL-3.0 and LPPL-1.3c and LPPL-1.0 and Artistic-1.0 and Apache-2.0 and MIT and BSD-3-Clause,1
LGPL3+,1
Public Domain and BSD 3-Clause,1
"MPLv2.0, MIT",1
ZPL 2.1,11
GPLv3.0,1
UCAR OSI approved,1
Waqef,1
CC BY 4.0,2
Proprietary,2
LPGLv2+,1
PSF or ZPL,1
wxWindows Library v3.1,1
freeware,1
BSD 3-Clause and BSD with advertising,1
WTFPL v2,1
LGPL-2.1 and GPL-2.0,1
ZPL-2.1,1
PSF 2 and ZPL 2.1,1
CUSTOM,1
GPL v2,3
Public Domain/MIT,1
LLVM-Exception,1
GPLv2 with Linking Exception,1
ZLIB,5
Google,1
ALPS,1
bzip2,1
"Apache 2.0 or BSD 3-Clause, PSF 2",1
MIT-like,2
GPL (== 2),1
GPL (>= 3.0),3
GNU GPL3,1
The University of Illinois/NCSA,1
GPL2 and GPL3,1
MIT and GPL,1
LGPL-2.1 or LGPL-3.0,1
"Apache, Version 2.0",1
LGPLv3.0,1
NIST,2
"MIT, GPL2",1
VMD,3
MPL 2,2
Freely Distributable,1
ZPL-2.0,1
None,2
CECILL,2
DSDP,1
"BSD, MIT, LDC",1
GNU Library or LGPL or BSD,1
"PSF 2, BSD",1
,239
Tcl/Tk,3
GPL v3.0,1
GPL 3 (with GCC Runtime Library Exception 3.1),3
Public-Domain,2
MIT/X11,1
NA,1
custom,2
"GPL-2,GPL-3",1
other,2
APACHE-2.0,16
BSD=3-Clause,1
Simplified BSD,1
GLP-2.0,1
CeCILL-2.1,1
GPL-2+,1
perl5,1
Zlib,2
Creative Commons Attribution 4.0,1
GPL2+,2
GNU Affero General Public v3 or later (AGPL-3.0+),1
CeCILL-B,6
OFL-1.1,2
Bitstream Vera Fonts,1
BSD-3.0,1
GNU (LGPLv3),1
CeCiLL-2.1,1
BSD Modification Variant,1
LGPL-2.0-or-later,2
Artistic,1
"LGPL, MIT",1
Apache Software,41
Other,3
ESGF,1
GNU Lesser General Public v2 (LGPLv2),2
Python 2.6.2,1
GNU General Public v3,1
"Qhull(BSD-like) For details, see COPYING.txt",1
APACHE,2
BSD-compatible,1
GPL-2.0+,2
LGPL v3.0,1
perl_5,2
GPL-2.0-or-later,31
GNU General Public v3 or later (GPLv3+),1
Copyright 2012. Bloomberg Finance L.P.,1
GPL-2 | GPL-3 | BSD_3_clause,1
Apache (>= 2.0),6
modified LGPL,1
ISC (ISCL),4
Apache (== 2.0),2
"MIT, Proprietary (Triangle), AGPL-3.0 (TetGen)",1
GNU General Public v2 or later (GPLv2+),2
GLP-3.0,1
Revised BSD,1
GLP 2.0,1
MIT?,1
CC BY-NC-SA 4.0,2
CeCILL,1
BSD_3_clause | GPL-2,1
OLDAP-2.8,1
APL 2.0,1
"BSD 2-Clause ""Simplified""",1
GPL (>= 2.1),1
ReportLab BSD derived,1
MPL (>= 2.0),1
Apache License 2.0,1
GNU General Public v3 (GPLv3),4
GNU GPLv3,1
CC-1.0,1
ISSL,1
OSMC-PL,1
The MIT (MIT),1
MINPACK,1
CC BY-SA 3.0,5
GNU GPL,1
BSD-2.0,1
LGPL-3.0+,1
GPL-2 AND LGPL-2.1 AND GPL-3,1
BSD-style,1
MPL 2.0 (Licence Publique Mozilla 2.0),1
Mozilla Public v1.1,1
AGPL v3.0,1
NIST public domain,1
Geant4,1
IUPAC/InChI-Trust Licence,1
PSFL,1
GNU Affero General Public v3 or later (AGPLv3+),3
MPL,1
MIT No Attribution,1
IGTF Federation,1
GNU-3.0,1
EUPL-1.1,3
LGPL-2.1-only,1
AGPL-3.0-or-later,1
Multiple,1
PROPRIETARY,1
MIT/X11 Derivative,1
BSD 3-Clasue,1
GPLv2 or BSD,6
MPL v2,1
Public domain | X/MIT | BSD-2/3/4-Clause | CC0 | CC-BY (v3.0 or later) | CC-BY-SA (v3.0 or later),1
GNU General Public v2 (GPLv2),1
GNU Lesser General Public v2 or later (LGPLv2+),1
LGPL (or GPL if released with AmberTools),1
CeCILL-2,4
GPL-2.0 | EPL-1.0,1
New BSD,1
GNU General Public (GPL),8
LGPL-v2.1,1
GNU Affero General Public v3,1
BSD-3-Clause-LBNL,3
LGPLv2/GPLv2,2
BSD-2-Clause AND BSD-3-Clause,1
The Unlicense,1
LGPL-2.1-or-later,8
EPICS Open,2
OFL,1
"SIL Open Font Lic., Version 1.1",1
Ubuntu Font Licence Version 1.0,1
Dual GPLv2 and BSD 2-Clause,1
X11,1
BSD custom 5-clause variant,1
CC-BY-SA-3.0,1
Blue Oak Model 1.0.0,1
UIUC,1
CC-BY-2.0,1
LGPL-3.0-or-later,6
SLAC Open,2
MIT & BSD-2-Clause,1
Artistic-2.0 (Restricts use),1
GPL-2.0 + Classpath,1
GPL-2.0-only,1
CDDL-1.0,5
BSD 3-Clause Modified,1
GPL-3.0-or-later AND Apache-2.0 AND CC0-1.0 AND CC-BY-SA-4.0,2
Eclipse Public v1.0,1
GPL-2.1,1
various,1
LGPL-v2.1-or-later,25
GPL-v2,9
LGPL-v2.-or-later,1
Apache Version 2.0,1
GNU Lesser General Public v3 (LGPLv3),1
GPL-3.0 AND Apache-2.0 AND BSD-3-Clause,1
CC-BY-SA-4.0,1
MIT AND Apache-2.0 AND OFL-1.1 AND Public-Domain AND DejaVu-Fonts,2
CECILL-C,1
GNU LGPL or BSD,1
unlicense,1

**Comment by CJ-Wright** [comment]
@isuruf do you want this to get into the next release? (I'd like to put something together soon so we can start the testing of the auto-merge capabilities)

**Comment by isuruf** [comment]
Go ahead. There's no conda package for `license-expression`, so it might take a while.

**Comment by scopatz** [comment]
This looks great @isuruf! But it does need a news entry.

**Comment by isuruf** [comment]
Do we want the check to be case-sensitive or not? CECILL-B vs CeCILL-B

**Comment by scopatz** [comment]
Case sensitive is probably better

**Comment by marcelotrevisani** [comment]
Just a note, I am doing something similar for ``grayskull`` but using fuzzy comparisons 
That might be interesting I think, I commented in the other post about that
https://github.com/conda-forge/cfep/issues/28#issuecomment-600875390

**Comment by isuruf** [comment]
I'm not sure I get you. How is that relevant here?

**Comment by jakirkham** [comment]
What happens when we have a [recipe like this]( https://github.com/conda-forge/hdf5-feedstock/blob/fe591e2385646867de5894761a144a9836317c82/recipe/meta.yaml#L191 )?

**Comment by isuruf** [comment]
You could make it `Other`.

**Comment by jakirkham** [comment]
In the `license` field? I'm not following.

**Comment by isuruf** [comment]
Yes. `license: Other`.

**Comment by jakirkham** [comment]
Usually we are providing better information in the `license` field though. I'm somewhat reluctant to loose that to appease a bot. Can we just leave it there? If so, what happens?

**Comment by isuruf** [comment]
>  If so, what happens?

The bot would suggest that the `license` field is not an SPDX identifier.

We could also allow anything that starts with `Other (`

**Comment by isuruf** [comment]
What better information is available? All license fields are in https://github.com/conda-forge/conda-smithy/pull/1220#issuecomment-578168001

**Comment by jakirkham** [comment]
Permitting `Other (...)` seems sensible.

It depends on the case. Usually someone has gone to the effort of explaining something informative about the atypical licensing situation of the recipe/package in that case.

**Comment by isuruf** [comment]
Can you open an issue or PR?

**Comment by jakirkham** [comment]
Sure noted in issue ( https://github.com/conda-forge/conda-smithy/issues/1263 ).

**Comment by marcelotrevisani** [comment]
> I'm not sure I get you. How is that relevant here?

Sorry, I think I was not clear.
``grayskull`` has a module to get all the spdx identifiers from opensource.org and it also has a function to normalize the license name received to a spdx doing some fuzzy comparisons. :)

**Comment by ocefpaf** [comment]
IMO that is a case where we should merge it regardless of the SPDX. The rule should be, use SPDX when possible.

One alternative is that, since we have a local copy of the SPDX identifiers, would be to add that in the list.

**Comment by h-vetinari** [comment]
Would it be possible to add support in this for patterns of the form:
`<license A> (details), <license B> (details), [etc.]`

There's such a case in the suitesparse feedstock. I tried to use SPDX-compliant identifiers, but the warning has not gone away:
```diff
-  license: LGPL v2 (AMD, BTF, etc), BSD 3-clause (UFget), GPL v2 (UMFPACK, RBIO, SPQR, GPUQRENGINE), Apache 2.0 (Metis)
+  license: LGPL-2.1-or-later (AMD, BTF, etc.), BSD-3-clause (UFget), GPL-2.0-or-later (UMFPACK, RBIO, SPQR, GPUQRENGINE), Apache-2.0 (Metis)
```

The [actual license](https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/master/LICENSE.txt) is quite involved, hence it's not a question of a simple "OR" (AFAIU).

**Comment by isuruf** [comment]
`license: LGPL-2.1-or-later AND BSD-3-clause AND GPL-2.0-or-later AND Apache-2.0` ?

**Comment by jakirkham** [comment]
But it depends on the components of SuiteSparse that are used, which license is relevant.

**Comment by isuruf** [comment]
That's true for lots of packages. The license for the package should indicate the license for the aggregate.

**Comment by h-vetinari** [comment]
> > > @isuruf: `license: LGPL-2.1-or-later AND BSD-3-clause AND GPL-2.0-or-later AND Apache-2.0`?

> > @jakirkham: But it depends on the components of SuiteSparse that are used, which license is relevant.

> @isuruf: That's true for lots of packages. The license for the package should indicate the license for the aggregate.

I wouldn't be comfortable to make that call (I'd err on the side of a more granular license).

What does an `AND`-conjunction mean, btw? `OR` is clear enough, but if the `AND` couples two incompatible licenses, it's non-sensical IMO.

I'd probably say that the parser should be made flexible enough to allow & ignore brackets after each license.

**Comment by isuruf** [comment]
> I'd probably say that the parser should be made flexible enough to allow & ignore brackets after each license.

This depends on whether we want to break with SPDX format. Currently we are strictly SPDX.

> What does an AND-conjunction mean, btw? OR is clear enough, but if the AND couples two incompatible licenses, it's non-sensical IMO.

In that case, you should split the package.

**Comment by h-vetinari** [comment]
> @isuruf: In that case, you should split the package.

I'm not a maintainer of that feedstock, CC @conda-forge/suitesparse 

Still, I don't think a split is ideal (IIUC, strictly speaking the combination of resulting subpackges could not be distributed together due to the conflicting licenses, which would be in direct contradiction to the fact that upstream *is* distributed like that)

**Comment by h-vetinari** [comment]
> @isuruf: In that case, you should split the package.

I'm not a maintainer of that feedstock, CC @conda-forge/suitesparse 

Still, I don't think a split is ideal (IIUC, strictly speaking the combination of resulting subpackges could not be distributed together due to the conflicting licenses, which would be in direct contradiction to the fact that upstream *is* distributed like that)

**Comment by jakirkham** [comment]
It might make sense to split the package, but that is a separate discussion IMO.

**Pull request merged**
