### PR TITLE
Option to skip webhooks

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [x] Added a ``news`` entry

We can switch to an org wide webhook to save some GH API calls.
cc @beckermr

### CODE REVIEW

**Comment by beckermr** [comment]
Ahhhhh. I was wondering about this when reading the code before. Makes sense to me.

**Comment by beckermr** [comment]
I think we are ok but we should double check the linting bot so it doesn’t try to lint or rerender our repos that are not feedstocks.

**Comment by isuruf** [comment]
Yes, this just adds an option to skip adding the webhook which is off by default. So, there's no change here in default behaviour at all.

**Comment by isuruf** [comment]
Merge?

**Comment by beckermr** [comment]
Yup let’s do it!

**Comment by isuruf** [comment]
Wait, CI is failing.

**Comment by isuruf** [comment]
CI is passing now

**Comment by beckermr** [comment]
Merge merge merge!

**Comment by isuruf** [comment]
Thanks @beckermr for the review.

**Pull request merged**
