### PR TITLE
Package tests

### LINKED ISSUE #846: Package tests
Is there a preferred way for me to package the tests? I was thinking of moving the tests under the `conda_smithy` dir.

### PR DESCRIPTION
**Pull request by CJ-Wright**
Close #846

### CODE REVIEW

**Comment by scopatz** [comment]
Same failure :frowning_face:

**Comment by CJ-Wright** [comment]
Yes the fix to conda build hasn't gone in yet.

**Comment by CJ-Wright** [comment]
@conda-forge/core ready for review!

**Comment by jakirkham** [comment]
Thanks @CJ-Wright :)

**Pull request merged**
