### PR TITLE
REF move automerge to conda-forge

### PR DESCRIPTION
**Pull request by beckermr**
This PR moves the automerge action to conda-forge.

Checklist
* [x] Added a ``news`` entry

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge/core this is ready to merge - once smithy is released with this, I will migrate the rest of the repos

**Comment by beckermr** [comment]
Yup. I am writing an admin migration to clean out any old files and add the new one here: https://github.com/conda-forge/admin-migrations/pull/33

**Comment by isuruf** [comment]
There's a mechanism in conda-smithy to remove old files.

**Comment by beckermr** [comment]
Ah ok. I can add that too. Is there a centralized spot, or should I code it up using the git tracking rm by hand?

**Comment by isuruf** [comment]
https://github.com/conda-forge/conda-smithy/blob/f84376747f0bcd753b3544ad912cc544c215b445/conda_smithy/configure_feedstock.py#L1498

**Comment by beckermr** [comment]
Thanks for the pointer @isuruf! Ready for another look!

**Comment by beckermr** [comment]
Thank you!

**Pull request merged**
