### PR TITLE
Add version update skip field to schema

### PR DESCRIPTION
**Pull request by mfisher87**
Checklist
* [x] Added a ``news`` entry

I believe this is the needed change to correspond with this one: https://github.com/regro/cf-scripts/pull/2646

Here's a feedstock I maintain which is failing lint due to leveraging this feature: https://github.com/conda-forge/quarto-feedstock/pull/50

### CODE REVIEW

**Comment by mfisher87** [comment]
@beckermr would you mind giving your input on this change? I think I found the right spot, but I assume I'm missing something :)

**Review by beckermr — CHANGES_REQUESTED** [review]
This needs a news item and I am pretty sure we need to regenerate the json schema after this change.

**Comment by beckermr** [comment]
Also thanks for the PR!

**Comment by mfisher87** [comment]
@beckermr I'm not used to this "news" format in use here, can you provide more details or a link to documentation? I'll also update the pull request template with that link as part of this PR to benefit future contributors :)

**Comment by mfisher87** [comment]
Same for generating the JSON schema actually :grin:

**Comment by beckermr** [comment]
Try running 

```
python conda_smithy/schema.py
```

from the top-level directory of the git repo and it should dump new json files that can be added.

**Review by beckermr — APPROVED** [review]

**Pull request merged**
