### PR TITLE
slightly modify Comic at end of README

### PR DESCRIPTION
**Pull request by sgbaird**
The current version is a bit off-color. Would it be possible to modify the image slightly?

Checklist
* [x] Added a ``news`` entry

### CODE REVIEW

**Comment by sgbaird** [comment]
@BastianZim, apologies for not being clearer. I edited the comic in PowerPoint to remove the reference to pornography at the very end. That's what I meant by off-color.

**Comment by BastianZim** [comment]
Ahh sorry now I have to clarify myself. I would keep it since it as is  since captures the spirit of the XKCD and thought that the wording is artistic freedom that we should tolerate. :)

**Comment by wolfv** [comment]
I did get that :) just wanted to point out that removing the link & just modifying the image might not be OK with the license. 
Personally, I don't mind either option -- keeping, changing or removing.

**Comment by sgbaird** [comment]
I added the links to the original and the xkcd license page. I figured a <sub> tag underneath the image worked well.

**Comment by timsnyder** [comment]
Think this can be closed as superseded by #1802

**Pull request closed without merging**
