### PR TITLE
ENH add checks if a build is a PR

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [x] Added a ``news`` entry

This PR adds explicit checks for whether or not a build is from a pull request. It then disables uploads from pull request builds.

### CODE REVIEW

**Review by isuruf — APPROVED** [review]
Wow. Great job.

**Comment by beckermr** [comment]
Drone is choking that if statement and I cannot figure out why...

**Comment by beckermr** [comment]
Any more comments here @conda-forge/core?

**Comment by beckermr** [comment]
Ok I'm gonna merge. Happy to fix up anything else later!

**Comment by jakirkham** [comment]
Thanks Matt! 😄

**Pull request merged**
