### PR TITLE
cfp recommends migrator_ts, so use that

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [x] Added a ``news`` entry

### CODE REVIEW

**Comment by isuruf** [comment]
@beckermr, this fixes a bug in earlier PR.

**Review by beckermr — APPROVED** [review]

**Comment by beckermr** [comment]
We should make sure all current migrators use the right key. I assume they do due to copy paste though.

**Comment by isuruf** [comment]
> I assume they do due to copy paste though.

Yes

**Comment by isuruf** [comment]
Thanks for the review

**Pull request merged**
