### PR TITLE
Fix run_osx_build not failing early on setup error

### PR DESCRIPTION
**Pull request by mbargull**
Checklist
* [ ] Added a ``news`` entry

In case of conda install connection errors, `conda-forge-ci-setup=3` would not get installed.
Previously, `run_osx_build.sh` would fail with a less explicit
```
+ make_build_number ./ ./recipe ./.ci_support/osx_64_MACOSX_DEPLOYMENT_TARGET11.0channel_targetsconda-forge_maincross_target_platformosx-arm64rust_archaarch64-apple-darwinrust_arch_envAARCH64_APPLE_DARWINrust_default_ccarm64-apple-darwin20.0.0-clangversion1.46.0.yaml
./.scripts/run_osx_build.sh: line 43: make_build_number: command not found
##[error]Bash exited with code '127'.
```
. Is there any reason to not `set -e` early on? If there are certain setup steps we are okay with to fail, we should run those explicitly with `may-fail || true`/`( set +e ; may-fail )`.

### CODE REVIEW

**Comment by isuruf** [comment]
Looks good. Have you tried this on a feedstock?

**Comment by mbargull** [comment]
I had not, but good idea in case there was a process that always had a non-zero exit code!
I tried it now for https://github.com/conda-forge/rust-activation-feedstock/pull/8 and it seems to work fine :).

**Comment by isuruf** [comment]
Thanks

**Comment by mbargull** [comment]
Thanks for the reviews and merges!

**Comment by mbargull** [comment]
(And misnamed filename fixes :D.)

**Pull request merged**
