### PR TITLE
Switched over default provider for osx and linux to azure.

### PR DESCRIPTION
**Pull request by mariusvniekerk**
Lets stop waiting for travis forever.

Checklist
* [x] Added a ``news`` entry

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
cc @conda-forge/core

**Comment by isuruf** [comment]
Travis-CI seems to be fine now. The only issue with this is permissions. Maintainers don't have access to azure

**Comment by mariusvniekerk** [comment]
I've seen that the restart buttons (on github checks) now seem to work again

**Comment by isuruf** [comment]
Would you mind sending a PR to docs repo about the azure buttons?

**Comment by mariusvniekerk** [comment]
https://github.com/conda-forge/conda-forge.github.io/pull/739

**Comment by scopatz** [comment]
This looks fine to me now. I will merge tomorrow if there are no further objections

**Comment by scopatz** [comment]
Thanks a ton @mariusvniekerk!

**Pull request merged**
