### PR TITLE
Fix README for multiple outputs

### PR DESCRIPTION
**Pull request by isuruf**
Example:

image

### CODE REVIEW

**Comment by ocefpaf** [comment]
Only you would think about that! Thanks!!

**Comment by isuruf** [comment]
Sure. Can you send a PR? Sooner the better. I don't want to change the readme after half the feedstocks have been changed.

**Comment by jakirkham** [comment]
Working on it...

**Comment by jakirkham** [comment]
Proposal in PR ( https://github.com/conda-forge/conda-smithy/pull/746 ) with a screenshot using the same feedstock.

**Pull request merged**
