### PR TITLE
Mention 'strict' channel priority in feedstock READMEs

### PR DESCRIPTION
**Pull request by phil-blain**
Checklist
* [x] Added a ``news`` entry

Closes https://github.com/conda-forge/conda-smithy/issues/1348

Bring the README template for feedstocks in line with the [conda-forge
documentation][1] by mentioning how to configure 'strict' channel
priority after adding the `{{ channel_name }}` channel.

[1]: https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge

### CODE REVIEW

**Comment by isuruf** [comment]
We haven't done this because we still have some issues in windows.

**Comment by ocefpaf** [comment]
> We haven't done this because we still have some issues in windows.

Are we tracking those?  though we had them solved. I'll preform some tests as soon as I get a Windows machine.

**Comment by beckermr** [comment]
We can add a statement that says this is useful and point to the docs even if windows is not quite working IMHO

**Comment by scopatz** [comment]
Maybe we can change the text here to mention the windows issue

**Pull request merged**
