### PR TITLE
Enable Travis build for ppc64le

### PR DESCRIPTION
**Pull request by jayfurmanek**
This PR is a continuation of: https://github.com/conda-forge/conda-smithy/pull/763  by @kamasubb

I've not seen activity on that PR, so I figured we should start fresh. I've resolved the merge conflicts that have popped up since 763 was opened, but have not yet tested it. I'll try and lead this work now and would like some feedback on where this one left off. Thanks!

=======
Added New Build Queue for PowerPC builds
Added changes to download and Install miniconda for PPC
Added changes to build conda-forge-build-setup

TODO:

- [x]    Build su-exec locally and copy
- [x]    Build tini locally and copy
- [x]    Build conda-forge-ci-setup locally and copy
- [x]    Merge conda-forge/conda-forge-pinning-feedstock#78 and release
- [x]    Merge conda-forge/docker-images#67 and upload to dockerhub
- [x]    Fix this PR to use docker.
- [ ]    Create a help-ppc64le team
- [ ]    Build su-exec using this PR
- [ ]    Build tini using this PR
- [ ]    Build conda-forge-ci-setup using this PR

### CODE REVIEW

**Comment by jayfurmanek** [comment]
@isuruf The templates have changed since your suggestions on #763 , let me know what you think of this new version. Thanks!

**Comment by jayfurmanek** [comment]
@ipoddar-ibm  FYI

**Comment by jayfurmanek** [comment]
So 1 out of 55 tests is failing. 
```
Traceback (most recent call last):
  File "/home/travis/build/conda-forge/conda-smithy/tests/test_configure_feedstock.py", line 168, in test_circle_osx
    assert not os.path.exists(travis_yml_file)
AssertionError: assert not True
```
I'm a little confused at why there is a `assert not` there on the yml file. I'll have to study that a bit more.

**Comment by isuruf** [comment]
See https://github.com/mariusvniekerk/conda-smithy/pull/1

**Pull request closed without merging**
