### PR TITLE
add option to install ATL components

### LINKED ISSUE #2062: Add azure option to install atl on Windows
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

It seems that now Windows Azure Pipelines images to not ship atl or anyhow require it to be re-installed manually (see https://github.com/actions/runner-images/issues/9873), that needs to be installed manually for recipes that need it, see:
* https://github.com/conda-forge/llvmdev-feedstock/pull/264#issuecomment-2128995491, https://github.com/conda-forge/llvmdev-feedstock/commit/221c9f3773f9cf17a95c34bc92316ca622488b65
* https://github.com/conda-forge/qt-main-feedstock/pull/269
* https://github.com/conda-forge/qt-main-feedstock/pull/288#issuecomment-2351442337

I may look into this eventually, but I need to get more familiar with conda-smithy codebase.

### Installed packages

```shell
.
```

### Environment info

```shell
.
```

### PR DESCRIPTION
**Pull request by h-vetinari**
Fixes #2062

This breaks on only a handful of feedstocks, but where it does happen it's very annoying to fix for every rerender (and non-obvious for those who don't know). Initially my hope was that MSFT would solve https://github.com/actions/runner-images/issues/9873, but after many months, it's time to admit that that won't happen.

### CODE REVIEW

**Review by beckermr — APPROVED** [review]
LGTM! I assume you have tested in feedstock? Assuming it works there, let's merge!

**Comment by jakirkham** [comment]
Will we want this on GHA too?

**Comment by h-vetinari** [comment]
> LGTM! I assume you have tested in feedstock? Assuming it works there, let's merge!

Have tested this successfully on llvmdev (an affected feedstock). :)

> Will we want this on GHA too?

I don't think this is relevant unless/until we start building such big packages on GHA. Also, the setting is currently under `AzureRunnerSettings`, so that also wouldn't make much sense for GHA. Let's add it when it becomes a concern.

**Comment by h-vetinari** [comment]
Hm, I had tested the rerender, but not in CI yet. The current version of this PR ends up producing
```yaml
jobs:
- job: win
  install_atl: true
  pool:
    vmImage: windows-2022
```
which azure stumbles over with:
```

**Comment by h-vetinari** [comment]
OK, as of the last commit, this is fixed now (i.e. CI for https://github.com/conda-forge/llvmdev-feedstock/pull/297/commits/54733d3ebc617b4dc3d8e646263465fa0c5ab9f6 is running fine).

**Pull request merged**
