### PR TITLE
Set default Python to 3.5 in appveyor.yml template

### PR DESCRIPTION
**Pull request by hadim**
Why not 3.5 by default ?

@ocefpaf

### CODE REVIEW

**Comment by ocefpaf** [comment]
Don't really have an opinion here. I believe the stack of tools we use are ready for `PY35` but I will leave this one for @pelson.

**Comment by jakirkham** [comment]
This should be safe to merge. Also we don't currently use `conda-build-all` or anything in the feedstocks (though there have been discussions at times).

That being said, I don't think this variable setting really matters. I believe it is just overridden by the matrix. So the only times it should matters is when we don't have Python as a build time dependency.

**Comment by jakirkham** [comment]
As reference, @pelson planned to [drop this line]( https://github.com/conda-forge/conda-smithy/pull/193/files#diff-a21d424d600d24e538028a242ff2da78L16 ) entirely as it doesn't really serve a purpose.

**Comment by jakirkham** [comment]
So there is a default still on these [lines]( https://github.com/conda-forge/conda-smithy/blob/ecfb5a71fd07214048b522e0840ebc3cb33e697f/conda_smithy/templates/appveyor.yml.tmpl#L14-L15 ). However, they will almost certainly be overridden. In fact, those lines probably should be removed as they should never be used.

To really get the intended effect, one should change this [line]( https://github.com/conda-forge/conda-smithy/blob/ecfb5a71fd07214048b522e0840ebc3cb33e697f/conda_smithy/configure_feedstock.py#L309 ) to `else`.

**Comment by jakirkham** [comment]
> To really get the intended effect, one should change this [line]( https://github.com/conda-forge/conda-smithy/blob/ecfb5a71fd07214048b522e0840ebc3cb33e697f/conda_smithy/configure_feedstock.py#L309 ) to `else`.

If you still are interested in this change @hadim , please submit a new PR with the change described.

**Pull request closed without merging**
