### PR TITLE
Update `.ci_support/README`

### PR DESCRIPTION
**Pull request by jakirkham**
Refresh's `.ci_support/README` to cover missed matrix elements that are expected. Also wraps text in the README to improve readability.

<hr>

Checklist
* [x] Added a ``news`` entry

### CODE REVIEW

**Review by galipremsagar — APPROVED** [review]

**Comment by jakirkham** [comment]
Changes can be seen in PR ( https://github.com/conda-forge/pyorc-feedstock/pull/21 ).

**Comment by jakirkham** [comment]
Thoughts @conda-forge/core? 🙂

**Review by xhochy — APPROVED** [review]

**Comment by jakirkham** [comment]
Any other thoughts on this @conda-forge/core? 🙂

**Review by beckermr — APPROVED** [review]

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
