### PR TITLE
lint jinja2 variables

### LINKED ISSUE #715: lint jinja2 variable spaces
Should we lint the jinja2 variable spaces?

### PR DESCRIPTION
**Pull request by justcalamari**
Closes #715

### CODE REVIEW

**Comment by CJ-Wright** [comment]
Would it be possible to add a test? (feel free to steal from the autotick bot's regex issue for examples :smile:)

**Comment by jakirkham** [comment]
Would be good to have at least these test cases if possible. Could add others, but think those catch the basic issues seen thus far.

```
{% set version="0.27.3" %}
{% set version = "0.27.3"%}
{%set version = "0.27.3" %}
```

**Comment by justcalamari** [comment]
Should we check that all Jinja2 variable definitions are at the top of the file or might there be a good reason to define a variable in the middles of the meta?

**Comment by jakirkham** [comment]
I wouldn’t. Recipes sometimes set them in other locations for good reasons (e.g. variables used for tests).

**Comment by CJ-Wright** [comment]
@justcalamari if you want you can put in a separate PR for single/double quoting.

**Comment by jakirkham** [comment]
Tests look good.

This isn't WIP any more, right? Care to remove that from the PR title?

What's the quoting change that you are mentioning?

**Comment by CJ-Wright** [comment]
@jakirkham single quote vs. double quote

**Comment by jakirkham** [comment]
Sorry not following. Is there a problem caused by picking either one or is this just about preferring one over the other?

**Comment by CJ-Wright** [comment]
Sorry, I was wondering if should we prefer double quote or single quote in the variables. If so I'd leave that discussion/code to another PR. (@justcalamari and I were discussing this offline at work the other day)

**Comment by jakirkham** [comment]
Would it be alright if we start with an issue first? Think we should get other people's feedback on this one first.

**Pull request merged**
