### PR TITLE
Fixed the bad travis client. Major improvement to the readme. Improved some of the exceptions.

### PR DESCRIPTION
**Pull request by pelson**
I've been using this branch to generate https://github.com/conda-forge/cycler-feedstock and am pretty happy with the result. To create the feedstock, it now looks like:

```
conda smithy init path_to_recipe
cd path_to_recipe-feedstock
conda smithy github-create
conda smithy register-feedstock-ci
conda smithy regenerate
git push upstream master
*done*
```

Clearly still some room for improvement, but slickness is improving.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@pelson I want to test this out, but first I tried to update the conda-smithy-feedstock. The current [version](https://github.com/conda-forge/conda-smithy-feedstock/blob/master/recipe/meta.yaml#L3) says `0.1.0dev`, but latest master says:

```shell
> python setup.py version
running version
keywords are unexpanded, not using
got version from VCS {'error': None, 'version': '0.0.1.dev71', 'dirty': False, 'full-revisionid': 'c99b30ba99ed03bc3afa33a4c9673d0b82ff44c3'}
Version: 0.0.1.dev71
 full-revisionid: c99b30ba99ed03bc3afa33a4c9673d0b82ff44c3
 dirty: False
```

I am unfamiliar versioneer there but I guess we need to tag a release to change this, right?

**Comment by pelson** [comment]
> I am unfamiliar versioneer there but I guess we need to tag a release to change this, right?

Aha. Yes, that would be necessary. I've got a few changes to put forwards, but I'd be happy enough to tag an early release when in the next week or so. Installing from source is also trivially easy.

**Comment by ocefpaf** [comment]
> Installing from source is also trivially easy.

I already did that.  Got stuck on `ruamel.std.argparse`

```python
> conda smithy init pyproj       
Traceback (most recent call last):
  File "/home/filipe/miniconda/bin/conda-smithy", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/filipe/miniconda/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/pkg_resources/__init__.py", line 3138, in <module>
  File "/home/filipe/miniconda/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/pkg_resources/__init__.py", line 3124, in _call_aside
  File "/home/filipe/miniconda/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/pkg_resources/__init__.py", line 3151, in _initialize_master_working_set
  File "/home/filipe/miniconda/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/pkg_resources/__init__.py", line 661, in _build_master
  File "/home/filipe/miniconda/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/pkg_resources/__init__.py", line 962, in require
  File "/home/filipe/miniconda/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/pkg_resources/__init__.py", line 849, in resolve
pkg_resources.DistributionNotFound: The 'ruamel.std.argparse>=0.5.1' distribution was not found and is required by ruamel.yaml
```

I guess we need to fix the `ruamel.yaml` dependencies first.

**Comment by pelson** [comment]
I think they have been packaged with conda-forge...

Notice how I have an environment starting with an underscore - that means I can install conda into it :wink::

```
conda env export -n _conda-smithy
name: _conda-smithy
dependencies:
- anaconda-client=1.2.1=py27_0
- clyent=1.2.0=py27_0
- conda=3.19.0=py27_0
- conda-build=1.18.2=py27_0
- conda-build-all=0.8.0=py27_0
- conda-env=2.4.5=py27_0
- gitdb=0.6.4=py27_0
- gitpython=1.0.1=py27_0
- jinja2=2.8=py27_0
- markupsafe=0.23=py27_0
- openssl=1.0.2d=0
- pip=7.1.2=py27_0
- pycosat=0.6.1=py27_0
- pycrypto=2.6.1=py27_0
- pygithub=1.21.0=py27_0
- python=2.7.11=0
- python-dateutil=2.4.2=py27_0
- pytz=2015.7=py27_0
- pyyaml=3.11=py27_1
- readline=6.2=2
- requests=2.9.0=py27_0
- ruamel.ordereddict=0.4.6=py27_0
- ruamel.yaml=0.10.5=py27_0
- setuptools=19.1.1=py27_0
- six=1.10.0=py27_0
- smmap=0.9.0=py27_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- wheel=0.26.0=py27_1
- yaml=0.1.6=0
- zlib=1.2.8=0
- pip:
  - appdirs==1.4.0
  - conda-smithy (/Users/pelson/dev/conda-forge/conda-smithy)==0.0.1.dev69 HEAD.detached.at.upstream
    master g80e0707
  - ipython==2.1.0
  - ruamel.base==1.0.0
  - ruamel.std.argparse==0.6.0
  - scikit-image (/Users/pelson/dev/scikit-image)==0.11.dev0
  - sphinxcontrib-napoleon==0.2.8
```

**Comment by pelson** [comment]
Also, looks like I *haven't* packaged all of the ruamel stuff (which frankly, is a bit of a mess).

**Comment by ocefpaf** [comment]
I got a weird issue when trying to package `ruamel.std.argparse`.  I will try again later and get back to you.

PS: Installing `ruamel.std.argparse` broke `site.py`.

```python
  Traceback (most recent call last):
    File "//home/filipe/miniconda/lib/python2.7/site.py", line 152, in addpackage
      exec line
    File "<string>", line 1, in <module>
  KeyError: 'ruamel'
```

**Comment by pelson** [comment]
> which frankly, is a bit of a mess

:wink:

**Comment by ocefpaf** [comment]
Yeah.  And I got it working without `ruamel.std.argparse` now... go figure.

**Comment by pelson** [comment]
> Yeah. And I got it working without ruamel.std.argparse now... go figure.

I removed the requirements.txt for this very reason. Glad you have it working.

**Pull request merged**
