### PR TITLE
Fix configs when value of a key in zip_keys is repeated

### PR DESCRIPTION
**Pull request by isuruf**
cc @anton-malakhov, @jakirkham

### CODE REVIEW

**Comment by sodre** [comment]
Is an preliminary build available somewhere in Anaconda.org? Can you push to your channel?

**Comment by isuruf** [comment]
No. you can do `pip install git+https://github.com/isuruf/conda-smithy@cxx`

**Comment by isuruf** [comment]
PR here was to fix the issues at https://github.com/conda-forge/tbb-feedstock/pull/28

**Comment by msarahan** [comment]
I think I understand what you're doing here in terms of reducing the top-level config.  I'm pretty sure that's correct.  You need to be very careful, though, that you don't just simply lose the loop over python.  The tricky part here is that python is zipped with the compiler, so it will be split out into 3 jobs.  You have to do something to collapse those 3 jobs back somehow, by detecting that python is not a top-level variable, and merging it appropriately with shared top-level variables.

Unix has 3 entries:
https://github.com/conda-forge/tbb-feedstock/commit/3ae6e5e674a316d7ba3b17cfe74abf82135a54c4#diff-b41481fa6aa06c79dccd3b6158244e26R8

Win should have 2 for VS2015 top-level config; 1 for VS2008 top-level config:
https://github.com/conda-forge/tbb-feedstock/commit/3ae6e5e674a316d7ba3b17cfe74abf82135a54c4#diff-4e3f5c16f29177cb83f39b89eec8cc47L8

That's all what I would call the optimal outcome.  If that's too annoying to figure out, the alternative is that the zipped stuff on windows should be creating more configs - with python zipped with the appropriate VS.

**Comment by isuruf** [comment]
> That's all what I would call the optimal outcome.

Me too

> If that's too annoying to figure out, the alternative is that the zipped stuff on windows should be creating more configs - with python zipped with the appropriate VS.

This is fixed in this PR. Look at the last rendering in the tbb PR. 2 python versions in VS2015 and 1 python version in VS2008.

**Comment by msarahan** [comment]
Yep, cool.  Nice work.  I'll go ahead and merge this.

**Pull request merged**
